---
sidebar: sidebar
permalink: br-limitations-kvm.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm
summary: This release of NetApp Backup and Recovery has the following known limitations. 
---

= Known limitations with NetApp Backup and Recovery for KVM workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

The following actions and configurations are not supported in the private preview version of KVM workloads in NetApp Backup and Recovery: 

== Unsupported actions

The following actions are not supported in the private preview release:

* Clone, mount, or unmount VMs
* Restore VMs to an alternate location
* Protect VMs stored on SAN
* Protect applications
* Backup or restore from object stores
* Edit protection groups
* Create protection groups using VMs from multiple KVM hosts
* Create user-defined backups (only backups initiated from the NetApp Console are supported)

== Unsupported configurations

The following configurations are not supported:

* Role-based access control (RBAC)
* Disks directly attached to the KVM host
* Disks spanned across multiple NFS mount points or shares
* RAW disk format
* Storage pool types other than NetFS (only NetFS is supported)
