---
sidebar: sidebar
permalink: br-limitations-oracle.html
keywords: NetApp Backup and Recovery, Oracle Database
summary: Review these NetApp Backup and recovery limitations before using Backup and Recovery in your environment.
---

= Known limitations with NetApp Backup and Recovery for Oracle Database workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platforms, devices, or features that do not work or do not work well with this version are listed here. Read these limitations carefully.

The following action is not supported in the preview version of Oracle Database workloads in NetApp Backup and Recovery: 

* After you perform an incomplete recovery by restoring a database to a specific point in time or SCN, if you later need to restore to a point before that recovery, you must also select *Control files* in the restore destination settings. Without restoring the control file, the database cannot be restored to a point earlier than the previous incomplete recovery. 
* In the Backup and Recovery preview release for NetApp Console local deployment, backups to object storage are supported only for ONTAP S3 and StorageGRID destinations. Backup archiving is not supported in this preview release.
* Offline backup