---
sidebar: sidebar
permalink: br-limitations-oracle.html
keywords: NetApp Backup and Recovery, Oracle Database
summary: Review these NetApp Backup and Recovery limitations before using Backup and Recovery in your environment.
---

= Known limitations with NetApp Backup and Recovery for Oracle Database workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Review the current limitations and unsupported actions for Oracle Database workloads in NetApp Backup and Recovery.

The following actions are not supported for Oracle Database workloads in the preview release of NetApp Backup and Recovery: 

* After you perform an incomplete recovery by restoring a database to a specific point in time or SCN, if you later need to restore to a point before that recovery, you must also select *Control files* in the restore destination settings. Without restoring the control file, the database cannot be restored to a point earlier than the previous incomplete recovery. 
* In the Backup and Recovery preview release for NetApp Console local deployment, backups to object storage are supported only for ONTAP S3 and StorageGRID destinations. Backup archiving is not supported in this preview release.
* Offline backups
