---
sidebar: sidebar
permalink: br-limitations-hyperv.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Hyper-V, SAP HANA database, virtual machine, vm
summary: NetApp Backup and Recovery needs to first discover data in order for you to use the service. During discovery, NetApp Backup and Recovery analyzes all volumes and files in systems within your organization. 
---

= Known limitations with NetApp Backup and Recovery for Hyper-V workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platforms, devices, or features that do not work or do not work well with this version are listed here. Read these limitations carefully.

== Unsupported actions

The following actions are not supported in the private preview version of Hyper-V workloads in NetApp Backup and Recovery: 

* Create resource groups using VMs from multiple Hyper-V hosts
* Restore VMs to an alternate location
* Spanning disks (across multiple CIFS shares)
* Protect VMs over SAN
* Edit protection groups
* Protect Hyper-V hosts that are clustered using System Center Virtual Machine Manager (SCVMM)
* You cannot restore VMs or VM data between systems with different CPU vendors (Intel to AMD or vice versa), regardless of the "Processor compatibility" setting in Hyper-V. This setting only supports compatibility between different generations of the same vendor (e.g., Intel to Intel or AMD to AMD).

NOTE: In the January 19 2026 release, you cannot upgrade the NetApp plugins for Hyper-V or Windows using the *Upgrade* option in the Actions menu. Instead, remove each Hyper-V host and add it again to update the plugins.