---
sidebar: sidebar
permalink: br-limitations-kvm.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm
summary: This release of NetApp Backup and Recovery has the following known limitations. 
---

= Known limitations with NetApp Backup and Recovery for KVM workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platforms, devices, or features that do not work or do not work well with this version are listed here. Read these limitations carefully.

The following actions and configurations are not supported in the private preview version of KVM workloads in NetApp Backup and Recovery: 

== Unsupported actions

The following actions are not supported in the private preview release:

* Clone, mount, or unmount VMs
* Restore VMs to an alternate location
* Protect VMs stored on SAN
* Protect applications
* Backup or restore from object stores
* Edit protection groups
* Create protection groups using VMs from multiple KVM hosts
* Create user-defined backups (only backups initiated from the NetApp Console are supported)

== Unsupported configurations

The following configurations are not supported:

* Role-based access control (RBAC)
* Disks directly attached to the KVM host
* Disks spanned across multiple NFS mount points or shares
* RAW disk format
* Storage pool types other than NetFS (only NetFS is supported)

== Unsupported legacy NetApp Console accounts
Legacy NetApp Console accounts don't support the features required to protect KVM workloads. Check if you are using a legacy account in the Console web UI. If you have a legacy Console account, create a new account before protecting KVM workloads.

.Steps

. From the NetApp Console menu, select *Administration > Identity and access*.
. Under *Organization*, check to see if an *Account ID* is shown next to the organization ID. 
+
If an *Account ID* is shown, you are using a legacy account.
. If you are using a legacy account, do the following:
.. Log out of the Console and then browse to the https://console.netapp.com/[Console login page^].
.. Select *Sign up* to create a new account.