---
sidebar: sidebar
permalink: br-limitations-kvm.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, SAP HANA database, virtual machine, vm
summary: This release of NetApp Backup and Recovery has the following known limitations.
---

= Known limitations with NetApp Backup and Recovery for KVM workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Review the current limitations for KVM workloads in NetApp Backup and Recovery.

The following unsupported actions and configurations apply to KVM workloads in NetApp Backup and Recovery: 

== Unsupported actions

The following actions are not supported:

* In the Backup and Recovery preview release for NetApp Console local deployment, backups to object storage are supported only for ONTAP S3 and StorageGRID destinations. Backup archiving is not supported in this preview release.
* Clone, mount, or unmount VMs
* Protect VMs stored on SAN
* Protect applications
* Create user-defined backups (only backups initiated from the NetApp Console are supported)

== Unsupported configurations

The following configurations are not supported:

* Role-based access control (RBAC)
* Disks directly attached to the KVM host
* Disks spanned across multiple NFS mount points or shares
* RAW disk format
* Storage pool types other than NetFS (only NetFS is supported)

== Troubleshooting notes
Note the following when you use KVM workloads with NetApp Backup and Recovery.

* Backups can fail if the QEMU Guest Agent is not running in a protected VM. To avoid this issue, ensure that the `qemu-guest-agent` daemon is running on the VM before you start the backup.