---
sidebar: sidebar
permalink: br-limitations-vmware.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, vmware, vcenter
summary: Review these NetApp Backup and Recovery limitations before using Backup and Recovery in your environment.
---

= Known limitations with NetApp Backup and Recovery for VMware workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platforms, devices, or features that do not work or do not work well with this version are listed here. Read these limitations carefully.

The following actions are not supported in VMware workloads in NetApp Backup and Recovery: 

* vVol support
* Email integration
* Role-based access control (RBAC) support

== Protection groups now use host time zone scheduling
Protection groups created before host-time-zone scheduling was introduced continue to run on their previously configured time zone (typically UTC). To use the vCenter time zone, you must re-create the schedules. Refresh the vCenter Server connection and then edit the protection group (for example, by renaming it) to re-create the schedules with the new time zone.