---
sidebar: sidebar
permalink: br-limitations-kvm.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm
summary: This release of NetApp Backup and Recovery has the following known limitations. 
---

= Known limitations with NetApp Backup and Recovery for KVM workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platforms, devices, or features that do not work or do not work well with this version are listed here. Read these limitations carefully.

The following actions and configurations are not supported in the private preview version of KVM workloads in NetApp Backup and Recovery: 

== Unsupported actions

The following actions are not supported in the private preview release:

* Clone, mount, or unmount VMs
* Restore VMs to an alternate location
* Protect VMs stored on SAN
* Protect applications
* Edit protection groups
* Create protection groups using VMs from multiple KVM hosts
* Create user-defined backups (only backups initiated from the NetApp Console are supported)

== Unsupported configurations

The following configurations are not supported:

* Role-based access control (RBAC)
* Disks directly attached to the KVM host
* Disks spanned across multiple NFS mount points or shares
* RAW disk format
* Storage pool types other than NetFS (only NetFS is supported)

== Troubleshooting notes
Make note of the following when using the private preview of KVM workloads with NetApp Backup and Recovery:

* To ensure that KVM workload restores complete successfully, make sure that the *Enable VM-consistent snapshot* setting is active in the protection policy you use for KVM backups.
* You cannot back up a storage pool with KVM hosts managed by Apache CloudStack unless you add all managed hosts to NetApp Backup and Recovery. As a workaround, add every CloudStack-managed KVM host to NetApp Backup and Recovery.
* You cannot back up a stopped VM that belongs to a protection group. As a workaround, remove the stopped VM from the protection group before starting the backup.