---
sidebar: sidebar
permalink: br-limitations-kvm.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, KVM, SAP HANA database, virtual machine, vm
summary: This release of NetApp Backup and Recovery has the following known limitations. 
---

= Known limitations with NetApp Backup and Recovery for KVM workloads
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platforms, devices, or features that do not work or do not work well with this version are listed here. Read these limitations carefully.

The following actions and configurations are not supported in KVM workloads in NetApp Backup and Recovery: 

== Unsupported actions

The following actions are not supported:

* Clone, mount, or unmount VMs
* Restore VMs to an alternate location
* Protect VMs stored on SAN
* Protect applications
* Create user-defined backups (only backups initiated from the NetApp Console are supported)

== Unsupported configurations

The following configurations are not supported:

* Role-based access control (RBAC)
* Disks directly attached to the KVM host
* Disks spanned across multiple NFS mount points or shares
* RAW disk format
* Storage pool types other than NetFS (only NetFS is supported)

== Troubleshooting notes
Make note of the following when using KVM workloads with NetApp Backup and Recovery.

* Backups can fail if the QEMU Guest Agent is not running in a protected VM. As a workaround, ensure the `qemu-guest-agent` daemon is running on the VM before starting the backup.