---
sidebar: sidebar
permalink: br-start-discover-hyperv.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Hyper-V, workloads, protect
summary: NetApp Backup and Recovery must discover Hyper-V virtual machines before you can protect them.  
---

= Discover Hyper-V workloads in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Backup and Recovery must discover Hyper-V virtual machines before you can protect them.

*Required Console role*
Backup and Recovery super admin. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

== Add a Hyper-V host and discover resources

Add Hyper-V host information and let NetApp Backup and Recovery discover virtual machines. Within each Console agent, select the systems where you want to discover the resources.  

NOTE: When you add Hyper-V hosts and discover resources, NetApp Backup and Recovery installs the NetApp Hyper-V plug-in and the NetApp SnapCenter Windows FileSystem plug-in on the Hyper-V host to help with managing and protecting virtual machines.

.Steps

. From the NetApp Console menu, select *Protection* > *Backup and recovery*. 
+
If this is your first time logging in to NetApp Backup and Recovery, you already have a system in the Console, but haven't discovered any resources, the "Welcome to the new NetApp Backup and Recovery" landing page appears and shows an option to *Discover resources*. 

. Select *Discover resources*.

. Enter the following information: 
.. *Workload type*: Select *Hyper-V*.
.. If you haven't yet stored credentials for this Hyper-V host, select *Add credentials*.
... Select the Console agent to use with this host.
... Enter a name for this credential.
... Enter the user name and password for the account.
... Select *Done*.
.. *Host registration*: Add a new Hyper-V host. Enter the host's FQDN or IP address, credentials, Console agent, and port number.
. Select *Discover*. 
+
TIP: This process might take a few minutes.

.Result
After NetApp Backup and Recovery discovers resources, the Inventory page displays the Hyper-V workload in the list of workloads.

== Continue to the NetApp Backup and Recovery Dashboard

.Steps

. To display the NetApp Backup and Recovery Dashboard, from the NetApp Console menu, select *Dashboard*.   

. Review the health of data protection. The number of at risk or protected workloads increases based on the newly discovered, protected, and backed up workloads.