---
sidebar: sidebar
permalink: br-start-configure-oracle-database.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle, configure
summary: Configure your Oracle database in NetApp Backup and Recovery.  
---

= Configure an Oracle database in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can change authentication and node settings for a new standalone or clustered Oracle database. NetApp Backup and Recovery protects databases without these changes. If your environment changes after discovery, you might need to update the database settings.

*Required Console role*
Backup and Recovery super admin. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

== Configure an Oracle database

Change the configuration for an Oracle database. 

.Steps

. From the NetApp Console menu, select *Protection > Backup and Recovery*.
. Under *Workloads*, select the *Oracle* tile.
. In the Oracle inventory, select the *Databases* menu.
. In the list of databases, select *Configure database* (standalone database) or *Configure RAC database* (clustered database) for the database you want to configure.
. *Configure database settings*: Configure authentication settings for the database. Choose *OS authentication* to authenticate with the operating system only, or *Database authentication* to authenticate with the database directly.
. *Configure RMAN catalog*: Set RMAN connection settings for the database. Select *Target control file* to use the RMAN target control file, or *Catalog database* to use the RMAN recovery catalog. If you choose *Catalog database*, select the credentials and Transparent Network Substrate (TNS) name to connect to the recovery catalog.
. *Configure nodes* (clustered databases only): Add or remove nodes from protection, or change node priority using the arrow buttons. Nodes with higher priority are protected first. Lower priority nodes are protected only if higher priority nodes are unreachable or unhealthy.

. When you are finished, select *Done*.

.Result
Backup and Recovery connects to the database using the new settings.

