---
sidebar: sidebar
permalink: br-start-faq.html
keywords: backup and recovery faq, NetApp Backup and Recovery frequently asked questions
summary: This FAQ can help if you're just looking for a quick answer to a question.
---

= Frequently asked questions for NetApp Backup and Recovery
:hardbreaks:
:icons: font
:imagesdir: ./media/

[.lead]
This FAQ can help if you're just looking for a quick answer to a question.

== Deployment

*Do you need a license to use NetApp Backup and Recovery preview version?*

You can use the following license types:

* Sign up for a 30-day free trial.
//* Purchase a pay-as-you-go (PAYGO) subscription with Amazon Web Services (AWS) Marketplace, and Microsoft Azure Marketplace (coming soon). 
//* Bring your own license (BYOL), which is a NetApp License File (NLF) that you obtain from your NetApp Sales Rep. You can use the license serial number to get the BYOL activated in NetApp Console.


*How do you enable NetApp Backup and Recovery?* 
NetApp Backup and Recovery does not require any enablement. The backup and recovery option is automatically enabled on the Console left navigation. 

To get going, you need to sign up or reach out to your NetApp Sales representative to try out Backup and Recovery. Then, when you use the Console agent, it will include the appropriate capabilities for the service.

To get started with NetApp Backup and Recovery, select "Start discovering workloads" from its initial landing page. 

*Is NetApp Backup and Recovery available in standard, restricted, and private modes?*
At this time, NetApp Backup and Recovery is available only in standard mode. Stay tuned for more. 

For an explanation about these modes across all NetApp data services, refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes^].

== Access

*What's the NetApp Backup and Recovery URL?*
For the URL, in a browser, enter: https://console.netapp.com/[https://console.netapp.com/backup-and-recovery^] to access the NetApp Console. 




*How are access permissions handled?*
Only Organization admins have the ability to initiate the service and discover workloads (because this involves committing to usage of a resource). Subsequent interactions can be done by any role.

*What device resolution is best?*
The recommended device resolution for NetApp Backup and Recovery is 1920x1080 or better. 

*Which browser should I use?*
Any modern browser will work. 


== Interaction with other services

*Is NetApp Backup and Recovery aware of protection settings made in NetApp ONTAP?*
Yes, NetApp Backup and Recovery discovers snapshot schedules set in ONTAP. 

*If you set a policy using NetApp Backup and Recovery, do you have to make future changes only in Backup and Recovery?* 
We recommend that you make policy changes from NetApp Backup and Recovery.

//*How does NetApp Backup and Recovery interact with SnapCenter?*

//NetApp Backup and Recovery uses the following products and services:

//* SnapCenter to discover and set snapshot and backup policies for application workloads

//* SnapCenter to perform file- and workload-consistent recovery 



== Workloads

*What makes up a workload?*
A workload is an application for the Preview 2025 version. A workload includes all volumes that are used by a single application instance. For example, a Microsoft SQL Server DB instance deployed on mssql3.host.com can have vol1 and vol2 for its data and logs, respectively. Those volumes together constitute the workload for that specific instance of the DB instance.

//A workload is an application, a VM, or a file share. A workload includes all volumes that are used by a single application instance. For example, an Oracle DB instance deployed on ora3.host.com can have vol1 and vol2 for its data and logs, respectively. Those volumes together constitute the workload for that specific instance of the Oracle DB instance.


*What workloads does NetApp Backup and Recovery support?*

For the Preview 2025 version, NetApp Backup and Recovery can identify the following workloads: Microsoft SQL Server applications.

//NetApp Backup and Recovery can identify the following workloads: Oracle, MySQL, file shares, VMs, and VM datastores.

//In addition, if you are using SnapCenter or SnapCenter for VMware, all workloads supported by those products are also identified in NetApp Backup and Recovery and NetApp Backup and Recovery can protect and recover these in a workload-consistent manner.


*What is a "protected" workload?*
In NetApp Backup and Recovery, a workload shows a "protected" status when it has a primary detection policy enabled. 

//Coming soon, this could also be that CISWS is monitoring user activity. 

*What is an "at risk" workload?*
If a workload does not have a primary detection policy enabled, it is "at risk" even if it has a backup and snapshot policy enabled. 


*New workload added, but doesn't appear yet*
If you added a new workload to your environment, initiate discovery again and apply protection policies to protect that new resource. 



== Protection policies


*Is NetApp Backup and Recovery aware of protection settings made in NetApp ONTAP?*

Yes, NetApp Backup and Recovery discovers snapshot schedules set in ONTAP and whether ARP and FPolicy are enabled in a discovered workload. The info you see initially in the Dashboard is aggregated from other NetApp solutions and products. 


*Is NetApp Backup and Recovery aware of policies already made in SnapCenter?*

Yes, if you have workloads managed in SnapCenter, the policies managed by those products are brought into NetApp Backup and Recovery.

*Can you modify policies carried over from SnapCenter?*

Yes, you can modify policies that were managed by SnapCenter within NetApp Backup and Recovery. 

*If policies exist from ONTAP (already enabled in System Manager such as ARP, FPolicy, and snapshots) are those changed in NetApp Backup and Recovery?*

No. NetApp Backup and Recovery does not modify any existing detection policies (ARP, FPolicy settings) from ONTAP.

*What happens if you add new policies in SnapCenter after signing up for NetApp Backup and Recovery?*

NetApp Backup and Recovery recognizes any new polices created in SnapCenter.

*Can you change policies from ONTAP?*

Yes, you can change policies from ONTAP in NetApp Backup and Recovery. You can also create new policies in NetApp Backup and Recovery and apply them to workloads. This action replaces existing ONTAP policies with the policies created in NetApp Backup and Recovery. 

