---
sidebar: sidebar
permalink: br-start-enable.html
keywords: backup, Backup and Recovery, enable backup, Console, service, local deployment
summary: Enable Backup and Recovery on a system in NetApp Console or NetApp Console local deployment.
---

= Enable NetApp Backup and Recovery for ONTAP volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Enable NetApp Backup and Recovery for a storage system in NetApp Console or NetApp Console local deployment before you protect ONTAP volumes. You can enable the service when you add a system or later.

== Enable Backup and Recovery in NetApp Console 
Enable the Backup and Recovery service in NetApp Console.

.Steps

. Select the *Volumes* menu.
. From the Volumes protection overview page, select *Backup Settings*.
. Identify the system that you want to protect and select *Activate backup*.
. Select *Next*.
. Select the source volumes to protect and select *Next*.
. In the Define backup strategy page, select the backup architecture, and then define the policies and other details for local snapshots, replicated volumes, and backup files. See the details for backup options from the initial volumes you activated in this system. Then select *Next*.
. Optionally, have Backup and Recovery automatically fix mismatched backup, snapshot, and replication labels.
. Review the backup settings for these volumes, and then select *Activate Backup*.
. The protected volumes appear on the *Volumes* overview page.

== Enable Backup and Recovery in NetApp Console local deployment

Enable the Backup and Recovery service in NetApp Console local deployment.

.Before you begin
Ensure that you have obtained a license for NetApp Backup and Recovery. See https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html#obtain-a-license-file[Obtain a license^] for more information.

.Steps

. From the NetApp Console menu, select *Storage* > *Fleets*.
. If needed, add your fleet by selecting *Add fleet*.
. Select *Administration* > *Licenses*.
. Select *Add license* to add a Backup and Recovery license. For more information on adding a license, see https://docs.netapp.com/us-en/console-licenses-subscriptions/task-manage-data-services-licenses.html#add-a-license[Add a license^].
. Select *Storage* > *Fleets* and then open the *Systems* menu.
. Select *Add* to add a system, enter the system details, and save the new system by selecting *Add*.
. Choose a system and select a cluster. In the information panel on the right, select *Enable* for the Backup and Recovery service.
. Select *Backup Volumes*.
. Select *Next*.
. Select the source volumes to protect and select *Next*.
. In the Define backup strategy page, select the backup architecture, and then define the policies and other details for local snapshots, replicated volumes, and backup files. See the details for backup options from the initial volumes you activated in this system. Then select *Next*.
. Optionally, have Backup and Recovery automatically fix mismatched backup, snapshot, and replication labels.
. Review the backup settings for these volumes, and then select *Activate Backup*.
. The protected volumes appear on the *Volumes* overview page.