---
sidebar: sidebar
permalink: br-start-discover-kubernetes.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes
summary: NetApp Backup and Recovery needs to first discover workloads in order for you to use the service.  
---

= Discover Kubernetes workloads in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Discover Kubernetes clusters and their workloads in NetApp Backup and Recovery so you can protect them with backup and recovery policies.

*Required NetApp Console role*
Backup and Recovery super admin. If you are protecting data stored on a Cloud Volumes ONTAP cluster, the Cloud Volumes ONTAP Admin role is also required. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].


== Discover Kubernetes workloads
In Backup and Recovery inventory, discover Kubernetes clusters and workloads in your environment. Adding a cluster enables you to register it in NetApp Backup and Recovery and discover its applications and resources for protection. You can optionally discover air-gapped local Kubernetes resources using NetApp Console local deployment.

[NOTE]
=====
When you discover a cluster currently protected with Trident Protect, any backup schedules used with Trident Protect are disabled during the discovery process, as Trident Protect backup schedules are not compatible with Backup and Recovery. To protect the cluster's applications, link:br-use-policies-create.html[create a new protection policy] or associate the applications with an existing policy. You can then remove the Trident Protect backup schedules if needed.
=====

.Steps
. Do one of the following:
+
* If you are discovering Kubernetes workloads for the first time, in NetApp Backup and Recovery, under *Workloads*, select the *Kubernetes* tile.
* If you have already discovered Kubernetes workloads, in NetApp Backup and Recovery, select *Inventory* > *Workloads* and then select *Discover resources*.

. Select the *Kubernetes* workload type.
. Enter a cluster name and choose a Console agent to use with the cluster.
+
Backup and Recovery provides instructions that change based on the installation type you select. If you use NetApp Console local deployment, you can choose instructions to discover air-gapped resources that have no external network connectivity.
. Choose an installation type to view the instructions for installing Trident Protect on your Kubernetes cluster:
+
* Select *Connected* to discover clusters that have external network connectivity.
* Select *Air-gapped* to discover clusters that have no external network connectivity.
+
[role="tabbed-block"]
====
.Connected discovery
--
[loweralpha,start=1]
. Follow the command line instructions that appear in Backup and Recovery. These steps ensure that Backup and Recovery can interact with the cluster.
--

.Air-gapped discovery

--
[loweralpha,start=1]
. Enter the URL of your private Docker container registry. This registry is used to download the Trident Protect and Trident Protect Connector images during the installation.
. If your private container registry requires authentication, use one of the following methods to configure registry credentials:
+
* *Node-level authentication*: Configure registry credentials in the container runtime on each node. Once configured, all pods can pull images without requiring additional Helm settings.
* *Kubernetes image pull secret*: Create a Kubernetes image pull secret in the `trident-protect` namespace, then reference it during the Helm upgrade step in the Trident Protect installation instructions:
+
[source,console]
----
--set trident-protect.imagePullSecrets[0].name=<pull-secret-name>
--set connector.imagePullSecrets[0].name=<pull-secret-name>
----
. Follow the command line instructions that appear in Backup and Recovery, adding the image pull secret information during the Helm step (if required). These steps ensure that Backup and Recovery can interact with the cluster.
--

====
//end of tabbed area

. After you complete the Trident Protect installation steps, select *Discover*.
+
The cluster is added to the inventory.
. Select *View* in the associated Kubernetes workload to see the list of applications, clusters, and namespaces for that workload.

== Continue to the NetApp Backup and Recovery Dashboard
Follow these steps to view the NetApp Backup and Recovery Dashboard and verify discovered resources.

. From the NetApp Console menu, select *Protection* > *Backup and recovery*.
. Select the Kubernetes workload tile.
. From the Backup and Recovery menu, select *Dashboard*.
. Review the health of data protection. The number of at risk or protected workloads increases based on the newly discovered, protected, and backed up workloads.
+
link:br-use-dashboard.html[Learn what the Dashboard shows you].