---
sidebar: sidebar
permalink: br-start-discover-kubernetes.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Kubernetes
summary: NetApp Backup and Recovery needs to first discover workloads in order for you to use the service.  
---

= Discover Kubernetes workloads in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Backup and Recovery needs to discover Kubernetes workloads before protecting them. 

*Required NetApp Console role*
Backup and Recovery super admin. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].


== Discover Kubernetes workloads
In Backup and Recovery inventory, discover Kubernetes workloads in your environment. Adding a workload adds a Kubernetes cluster to NetApp Backup and Recovery. You can then add applications and protect cluster resources.

[NOTE]
=====
When you discover a cluster that is currently protected with Trident Protect, any backup schedules that were used with Trident Protect are disabled during the discovery process (Trident Protect backup schedules are not compatible with Backup and Recovery). To protect the cluster's applications, link:br-use-policies-create.html[create a new protection policy] or associate the applications with an existing policy. You can then remove the Trident Protect backup schedules if needed.
=====

.Steps
. Do one of the following:
+
* If you are discovering Kubernetes workloads for the first time, in NetApp Backup and Recovery, under *Workloads*, select the *Kubernetes* tile.
* If you have already discovered Kubernetes workloads, in NetApp Backup and Recovery, select *Inventory* > *Workloads* and then select *Discover resources*.

. Select the *Kubernetes* workload type.
. Enter a cluster name and choose a connector to use with the cluster.
. Follow the command line instructions that appear:
+
* Create a Trident Protect namespace
* Create a Kubernetes secret
* Add a Helm repository
* Install or upgrade Trident Protect and the Trident Protect connector
+
These steps ensure that NetApp Backup and Recovery can interact with the cluster.
. After you complete the steps, select *Discover*.
+
The cluster is added to the inventory.
. Select *View* in the associated Kubernetes workload to see the list of applications, clusters, and namespaces for that workload.

== Continue to the NetApp Backup and Recovery Dashboard
Follow these steps to view the NetApp Backup and Recovery Dashboard. 

. From the NetApp Console menu, select *Protection* > *Backup and recovery*.
. Select a workload tile (for example, Microsoft SQL Server).
. From the Backup and Recovery menu, select *Dashboard*.

. Review the health of data protection. The number of at risk or protected workloads increases based on the newly discovered, protected, and backed up workloads.  
+
link:br-use-dashboard.html[Learn what the Dashboard shows you].