---
sidebar: sidebar
permalink: br-start-login.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: You use NetApp Console to log in to NetApp Backup and Recovery service. 
---

= Log in to NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You use the NetApp Console to log in to NetApp Backup and Recovery. 

NetApp Backup and Recovery uses identity and access management to control what each user can do. 

For details about the actions that each role can perform, see link:reference-roles.html[NetApp Backup and Recovery user roles].

To log in to the NetApp Console, you can use your NetApp Support Site credentials or you can sign up for a NetApp Console login using your email and a password. https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html[Learn more about logging in^].

*Required NetApp Console role*
Backup and Recovery super admin or Backup and Recovery restore admin role. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

To add a Console agent, you must have the Backup and Recovery super admin role. 

.Steps

. Open a web browser and go to the https://console.netapp.com/[NetApp Console^].
+ 
The NetApp Console login page appears.
. Log in to the Console. 
. From the Console left navigation, select *Protection* > *Backup and Recovery*. 
+
* If this is your first time logging in to Backup and Recovery and you haven't yet added a system to the *Systems* page, the Backup and Recovery displays the "Welcome to the new NetApp Backup and Recovery" landing page and provides an option to add a system. For details about adding a system to the *Systems* page, refer to https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html[Getting started with NetApp Console standard mode^].
* If this is your first time logging in to Backup and Recovery and you have already added a system to the *Systems* page, but haven't discovered any resources, the "Welcome to the new NetApp Backup and Recovery" landing page appears and shows an option to *Discover resources*. 

. If you haven't done so already, select the *Discover and manage* option. 
+
* For Microsoft SQL Server workloads, refer to link:br-start-discover.html[Discover Microsoft SQL Server workloads].
* For VMware workloads, refer to link:br-use-vmware-discovery.html[Discover VMware workloads].
* For KVM workloads, refer to link:br-start-discover-kvm.html[Discover KVM workloads].
* For Oracle workloads, refer to link:br-start-discover-oracle.html[Discover Oracle workloads].
* For Hyper-V workloads, refer to link:br-start-discover-hyperv.html[Discover Hyper-V workloads].
* For Kubernetes workloads, refer to link:br-start-discover-kubernetes.html[Discover Kubernetes workloads].
 



