---
sidebar: sidebar
permalink: br-start-discover-oracle.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle
summary: NetApp Backup and Recovery must first discover workloads before it can protect them.
---

= Discover Oracle Database workloads in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Discover Oracle Database workloads in NetApp Backup and Recovery so that you can protect them with backups and snapshots.

*Required NetApp Console role*
Backup and Recovery super admin. Learn about link:reference-roles.html[Backup and Recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

== Configure DNS for air-gapped host discovery in NetApp Console local deployment
include::_include/dns-fix-air-gapped-db-discovery.adoc[]

== Add an Oracle Database host and discover resources

Add Oracle Database host information and let NetApp Backup and Recovery discover workloads. For each Console agent, select the systems to discover.

.Steps

. From the NetApp Console menu, select *Protection* > *Backup and Recovery*.
. Under *Workloads*, select the *Oracle* tile.
. Select *Discover resources*.

. Select *Oracle* for the *Workload type* field.
. If you haven't yet stored credentials for this Oracle Database host, select *Add credentials*.
.. Select the Console agent to use with this host.
.. Enter a name for this credential.
.. Enter the user name and password for the account.
.. Select *Done*.
. *Host registration*: Add a new Oracle Database host. In the *Host FQDN or IP address* field, enter the host's FQDN or IP address. For clustered databases, you can enter the FQDN or IP address of any node in the cluster. Then provide credentials, the Console agent, and the port number.

. (Optional) If you choose credentials for a non-root user, do the following:
.. For instructions on adding the selected non-root user to the sudoers file on the Oracle Database host, select *Configure sudoers*.
.. Follow the instructions in the dialog, enable the checkbox when complete, and select *Done*.
. *Advanced settings*: Do the following:
.. Enter the port and installation path to use for the NetApp plug-in. The plug-in enables communication between the Oracle Database host and NetApp Backup and Recovery.
.. Choose whether to allow NetApp Backup and Recovery to install the plug-in automatically on each host or skip the automatic plug-in installation for all hosts. Select *Show me how* for manual installation instructions.
+
[NOTE]
====
NetApp Backup and Recovery connects to each host via SSH to install the plug-in automatically. Enable *Use manual installation* when any of the following apply:

* One or more hosts are not running the SSH service.
* Any host already has the NetApp plug-in (including if only some cluster members do).
* You prefer to install the plug-in on each host manually.
====

.. If the database host is clustered, enable the *Add all hosts in the cluster* option to discover all hosts in the cluster. 
.. Choose whether to run pre-installation checks on each host before automatically installing the plug-in. If checks fail, automatic plug-in installation stops. To bypass the checks and install anyway, enable *Skip optional preinstall checks* (enabled automatically if you choose manual installation).
. Select *Discover*.
+
TIP: Adding resources can take several minutes. To see the progress, select *Track progress* in the status dialog at the bottom of the Inventory page or select *Monitoring* from the left navigation.

.Result
The Oracle Database workload appears in the workload list on the Inventory page.  

== Continue to the NetApp Backup and Recovery Dashboard

. From the NetApp Console menu, select *Protection* > *Backup and Recovery*.
. Select a workload tile (for example, Oracle Database).
. From the Backup and Recovery menu, select *Dashboard*.
. Review the health of data protection. The number of at-risk or protected workloads increases based on the newly discovered, protected, and backed up workloads.