---
sidebar: sidebar
permalink: br-start-discover-oracle.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, workloads, protect, Oracle
summary: NetApp Backup and Recovery needs to first discover workloads in order for you to protect them.  
---

= Discover Oracle Database workloads in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Discovering Oracle databases enables NetApp Backup and Recovery to protect them by creating and restoring backups and snapshots.

*Required Console role*
Backup and Recovery super admin. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

== Add an Oracle Database host and discover resources

Add Oracle host information and let NetApp Backup and Recovery discover workloads. Within each Console agent, select the systems where you want to discover workloads. 

.Steps

. From the NetApp Console menu, select *Protection > Backup and Recovery*.
. Under *Workloads*, select the *Oracle* tile.
. Select *Discover resources*.

. Select *Oracle* for the *Workload type* field.
. If you haven't yet stored credentials for this Oracle Database host, select *Add credentials*.
.. Select the Console agent to use with this host.
.. Enter a name for this credential.
.. Enter the user name and password for the account.
.. Select *Done*.
. *Host registration*: Add a new Oracle Database host. In the *Host FQDN or IP address* field, enter the host's FQDN or IP address - for clustered databases you can enter the FQDN or IP of any node in the cluster. Then provide credentials, the Console agent, and the port number.

. (Optional) If you choose credentials for a non-root user, do the following:
.. For instructions on how to add the non-root user you have selected to the sudoers file on the Oracle Database host, select *Configure sudoers*.
.. Follow the instructions in the dialog, enable the checkbox when complete, and select *Done*.
. *Advanced settings*: Do the following:
.. Enter the port and installation path to use for the NetApp plug-in. The plug-in enables communication between the Oracle Database host and NetApp Backup and Recovery.
.. Choose whether to allow NetApp Backup and Recovery to install the plug-in automatically on each host or skip the automatic plug-in installation for all hosts. Select *Show me how* for manual installation instructions.
+
[NOTE]
====
Backup and Recovery connects to each host via SSH to install the plug-in automatically. Enable *Use manual installation* when any of the following apply:

* One or more hosts are not running the SSH service.
* Any host already has the NetApp plug-in (including if only some cluster members do).
* You prefer to install the plug-in on each host manually.
====

.. If the database host is clustered, enable the *Add all hosts in the cluster* option to discover all hosts in the cluster. 
.. Choose whether to run pre-installation checks on each host before automatically installing the plug-in. If checks fail, automatic plug-in installation stops. To bypass the checks and install anyway, enable *Skip optional preinstall checks* (enabled automatically if you choose manual installation).
. Select *Discover*.
+
TIP: Adding resources can take several minutes. To see the progress, select *Track progress* in the status dialog at the bottom of the Inventory page or select *Monitoring* from the left-side menu.

.Result
The Oracle Database workload is displayed in the list of workloads on the Inventory page.  

== Continue to the NetApp Backup and Recovery Dashboard

. From the NetApp Console menu, select *Protection* > *Backup and recovery*.
. Select a workload tile (for example, Microsoft SQL Server).
. From the Backup and Recovery menu, select *Dashboard*.
. Review the health of data protection. The number of at risk or protected workloads increases based on the newly discovered, protected, and backed up workloads.