---
sidebar: sidebar
permalink: br-start-discover-kvm.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, KVM, workloads, protect
summary: NetApp Backup and Recovery needs to first discover workloads in order for you to protect them.  
---

= Discover KVM workloads in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Backup and Recovery needs to discover KVM hosts and virtual machines before protecting them. 

*Required Console role*
Backup and Recovery super admin. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

== Add a KVM host and discover resources

Add KVM host information and let NetApp Backup and Recovery discover workloads. Within each Console agent, select the systems where you want to discover workloads.

//.Before you begin
//If you use a management platform to manage KVM hosts and VMs, you need to integrate the management platform with Backup and Recovery so that you can discover the managed resources. Refer to link:br-start-configure.html#add-a-kvm-management-platform[Backup and Recovery global settings] for instructions.

.Steps

. From the NetApp Console menu, select *Protection > Backup and Recovery*.
. Select the KVM tile.
+
If you are logging in to Backup and Recovery for the first time and have a system in the Console but no discovered resources, the _Welcome to the new NetApp Backup and Recovery_ page appears with an option to *Discover resources*.

. Select *Discover resources*.

. Enter the following information: 
.. *Workload type*: Select *KVM*.
.. If you use a management platform to manage KVM resources and haven't yet integrated it with Backup and Recovery, select *Add management platform*.
... Enter the following information:
+
* *Management platform IP address or FQDN*: Enter the IP address or fully qualified domain name of the management platform.
* *API key*: Enter the API key to use to authenticate API requests.
* *Secret Key*: Enter the secret key to use to authenticate API requests.
* *Port*: Enter the port to use for communication between Backup and Recovery and the management platform.
* *Agents*: Select a Console agent to use to facilitate communication between Backup and Recovery and the management platform.
... When finished, select *Add*.
.. *KVM settings*: Add a new KVM host by entering the following information:
+
* *KVM FQDN or IP address*: Enter the host's FQDN or IP address.
* *Credentials*: Enter the username and password for the KVM host.
* *Console agent*: Choose the Console agent to use for communication between Backup and Recovery and the KVM host.
* *Port number*: Enter the port to use for communication between Backup and Recovery and the KVM host.
* *Management platform*: If the KVM host is managed and you have added the management platform to Backup and Recovery, select the management platform from the list.
. Select *Discover*. 
+
TIP: This process might take a few minutes.

.Result
The KVM workload is displayed in the list of workloads on the Inventory page.

//.. If you haven't yet stored credentials for this KVM host, select *Add credentials*.
//... Select the Console agent to use with this host.
//... Enter a name for this credential.
//... Choose whether to use root credentials or non-root credentials.
//... Enter the user name and password for the account.
//... Select *Done*.

== Continue to the NetApp Backup and Recovery Dashboard

.Steps

. From the NetApp Console menu, select *Protection* > *Backup and recovery*.
. Select a workload tile (for example, Microsoft SQL Server).
. From the Backup and Recovery menu, select *Dashboard*.
. Review the health of data protection. The number of at risk or protected workloads increases based on the newly discovered, protected, and backed up workloads.
