---
sidebar: sidebar
permalink: br-use-hyperv-restore.html
keywords: restore, vm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, Amazon Web services, AWS, NetApp Backup and Recovery
summary: Protect your Hyper-V workloads with NetApp Backup and Recovery. 
---

= Restore Hyper-V workloads with NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Restore Hyper-V workloads from snapshots, from a workload backup replicated to secondary storage, or from backups stored in object storage using NetApp Backup and Recovery. 

.Restore from these locations

You can restore workloads from different starting locations: 

* Restore from a primary location (local snapshot)
* Restore from a replicated resource on secondary storage
* Restore from an object storage backup

.Restore to these points   

You can restore data to these points: 

* Restore to the original location
* Restore to an alternate location

.Restore from object storage considerations

If you select a backup file in object storage, and ransomware protection is active for that backup (if you enabled DataLock and Ransomware Resilience in the backup policy), then you are prompted to run an additional integrity check on the backup file before restoring the data. We recommend that you perform the scan. 

TIP: You'll incur extra egress costs from your cloud provider to access the contents of the backup file.


== How restoring workloads works

When you restore workloads, the following occurs: 

* When you restore a workload from a local backup file, NetApp Backup and Recovery creates a _new_ resource using the data from the backup. 

* When you restore from a replicated workload, you can restore the workload to the original system or to an on-premises ONTAP system.


//== Restore methods

//You can restore workloads using one of the following methods. Typically, choose a method based on your restore needs:

From the Restore page, you can restore a resource, even if you don't remember the exact name, the location in which it resides, or the date when it was last in good shape. You can search for the snapshot using filters. 

//* *From the Inventory page (also known as Browse & Restore)*: Use this when you need to restore a specific resource from the last week or month -- and you know the name and location of the resource, and the date when it was last in good shape. You browse through a list of resources to find the one you want to restore.

//Inventory is browse and restore. Restore page is Search and restore. 



== Restore Hyper-V workloads

Restore Hyper-V workloads using the Restore menu. You can search for the snapshot by its name or by using filters. 

*Required Console role*
Backup and Recovery super admin or Backup and Recovery restore admin role. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

.Steps

. From the NetApp Backup and Recovery menu, select *Restore*.
. From the drop-down list to the right of the name search field, select *Hyper-V*. 

. Enter the name of the resource you want to restore or filter for the VM name, VM host, or storage pool where the resource that you want to restore is located. 
+
A list of snapshots appears that match your search criteria.
. Select the *Restore* button for the snapshot that you want to restore. 
+
A list of possible restore points appears.
. Select the restore point that you want to use.
. Select a snapshot source location.
. Select *Next* to continue.
. Choose the restore destination and settings:
+
[discrete]
===== Destination selection
+
[role="tabbed-block"]
====

.Restore to original location

--

.. Select the *Original location* pane.
When you restore to the original location, you can view the destination settings by expanding the *Destination settings* section, but you cannot change them.

.. In the *Post-restore options* section, consider the following option:
+ 
* *Start the virtual machine*: Enable this option to boot the new virtual machine after it is restored.

--

.Restore to alternate location

--

.. Select the *Alternate location* pane.
.. In the *Destination settings*: section, enter the following information:
+
* *Hyper-V FQDN or IP address*: Enter the fully qualified domain name or IP address of the destination Hyper-V host.
* *Network*: Select the destination network where you want to restore the snapshot.
* *Virtual machine name*: Enter the name of the VM that you want to restore.
* *Destination location*: Enter the destination folder or CIFS share that should contain the restored data.

.. In the *Pre restore options* section, consider the following options:
+
* *Quick restore*: Enable this option to make the restored VM available immediately. Only the files needed to run the VM are restored from the object store, rather than the entire volume.

.. In the *Post restore options* section, consider the following options:
+
* *Start the virtual machine*: Enable this option to boot the new virtual machine after it is restored.

--

====

. Select *Restore*.