---
sidebar: sidebar
permalink: br-use-dashboard.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, backup, recovery, dashboard, view, health, status, alerts, notifications
summary: Monitoring the health of your workloads ensures that you are aware of issues with workload protection and can take steps to resolve them. View the status of your backups and restores and respond to any alerts that appear on the NetApp Backup and Recovery Dashboard. You can review the Protection summary, Restore summary, System summary, and more.
---

= View protection health on the NetApp Backup and Recovery Dashboard
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Monitoring the health of your workloads ensures that you are aware of issues with workload protection and can take steps to resolve them. View the status of your backups and restores on the NetApp Backup and Recovery Dashboard. You can review the system summary, Protection summary, Job summary, Restore summary, and more. 


*Required NetApp Console role*
Storage viewer, Backup and Recovery super admin, Backup and Recovery backup admin, Backup and Recovery restore admin, Backup and Recovery clone admin, or Backup and Recovery viewer role. Learn about link:reference-roles.html[Backup and recovery roles and privileges]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^]. 

.Steps

. From the NetApp Console menu, select *Protection* > *Backup and recovery*.
. Select a workload tile (for example, Microsoft SQL Server).
. From the Backup and Recovery menu, select *Dashboard*.
+
You can review the following types of information:
+
* Number of hosts or VMs discovered
* Number of Kubernetes clusters discovered
* Number of backup targets on object storage 
* Number of vCenters 
* Number of storage clusters in ONTAP


== View the Protection summary

Review the following information in the Protection summary: 

* The total number of protected and unprotected databases, VMs, and datastores. 
+
TIP: A protected database is one that has a backup policy assigned. An unprotected database is one that doesn't have a backup policy assigned to it.
* The number of backups that were successful, have a warning, or have failed.
* The total capacity discovered by the backup service and the capacity that is protected versus unprotected. Hover over the "*i*" icon to see the details.



== View the Job summary

Review the total jobs completed, running or failed in the Job summary.  

.Steps 

. For each job distribution, change a filter to show the summary of failed, running and complete based on the number of days, for example, the last 30 days, last 7 days, last 24 hours, or last 1 year.

. View details of the failed, running and complete jobs by selecting *View job monitoring*.

 

== View the Restore summary

Review the following information on the Restore summary: 

* The total number of restore jobs performed
* The total amount of capacity that has been restored
* The number of restore jobs performed on local, secondary, and object storage. Hover over the chart to see the details.





