---
sidebar: sidebar
permalink: br-use-mssql-restore-overview.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery
summary: Backups of your data are available for restore from the locations where you created backups, which includes snapshot, replications, and backups in object storage. Review the restore-from locations, restore points, and resource types to restore.
---

= Restore Microsoft SQL workloads overview using NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Backups of your Microsoft SQL Server data from NetApp Backup and Recovery are available for restore from the locations where you moved the backups: snapshots, replications, or backups in object storage. You can restore a workload to the original system, to a different system that's using the same cloud account, or to an on-premises ONTAP system. Review the restore-from locations, restore points, and resource types to restore.

//different types of restore operations, volume restore or file/folder restore, Browse and restore vs Search and restore)

.Restore from these locations

You can restore workloads from different starting locations: 

* Restore from a primary location
* Restore from a replicated resource
* Restore from an object store backup

.Restore to these points   

You can restore data to the latest snapshot or to these points: 

* Restore from snapshots
* Restore to a specific point in time. This is helpful if you know the name and location of the file, and the date when it was last in good shape. 
* Restore to the latest backup 


== What's next

For details on how to restore workloads, see link:br-use-mssql-restore.html[Restore workloads].     

