---
sidebar: sidebar
permalink: br-use-back-up-now-kubernetes-applications-web-ui.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter
summary: Manually create on-demand backups of Kubernetes applications using the NetApp Backup and Recovery web UI.  
---

= Back up a Kubernetes application using the NetApp Backup and Recovery web UI
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Use the web UI to perform an on-demand backup of a Kubernetes application.

.Required NetApp Console role

Backup and Recovery super admin or Backup and Recovery backup admin. link:reference-roles.html[Learn about NetApp Backup and Recovery access roles]. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

== Back up a Kubernetes application
Manually create a backup of a Kubernetes application to establish a baseline for future backups and snapshots, or to ensure the most recent data is protected.

.Steps
. In NetApp Backup and Recovery, select *Inventory*.
. Choose a Kubernetes instance and select *View* to access the resources associated with that instance.
. Select the *Applications* tab.
. In the applications list, select an application you want to back up and choose the associated Actions menu.
. Select *Backup now*.
. Confirm the correct application is selected.
. Select *Back up*.

.Result
The Console creates a backup of the application and displays the progress in the *Monitoring* area of Backup and Recovery. The backup is created based on the protection policy associated with the application.