---
sidebar: sidebar
permalink: br-use-kvm-restore.html
keywords: restore, vm, kvm, virtual machine, snapshots, object storage, cloud storage, backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: Protect your KVM workloads with NetApp Backup and Recovery. 
---

= Restore KVM virtual machines with NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Restore KVM virtual machines from snapshots, from a protection group backup replicated to secondary storage, or from backups stored in object storage using NetApp Backup and Recovery.

//Restore KVM virtual machines from a protection group backup replicated to secondary storage using NetApp Backup and Recovery.

//You can restore a workload to the original working environment, to a different working environment that's using the same cloud account, or to an on-premises ONTAP system. 

//different types of restore operations, volume restore or file/folder restore, Browse and restore vs Search and restore)

.Restore from these locations

You can restore virtual machines from different starting locations: 

* Restore from a primary location (local snapshot)
* Restore from a replicated resource on secondary storage
* Restore from an object storage backup

.Restore to these points   

You can restore data to these points: 

* Restore to the original location
* Restore to an alternate location

.Restore from object storage considerations

If you select a backup file in object storage, and ransomware protection is active for that backup (if you enabled DataLock and Ransomware Resilience in the backup policy), then you are prompted to run an additional integrity check on the backup file before restoring the data. We recommend that you perform the scan. 

TIP: You'll incur extra egress costs from your cloud provider to access the contents of the backup file.


== How restoring virtual machines works

When you restore virtual machines, the following occurs: 

* When you restore a workload from a local backup file, NetApp Backup and Recovery creates a _new_ resource using the data from the backup. 

* When you restore from a replicated VM, you can restore it to the original system or to an on-premises ONTAP system.

* When you restore a backup from object storage, you can restore the data to the original system or to an on-premises ONTAP system.

From the Restore page, you can restore a VM, even if you don't remember the exact name, the location in which it resides, or the date when it was last in good shape. You can search for the snapshot using filters. 

//* *From the Inventory page (also known as Browse & Restore)*: Use this when you need to restore a specific resource from the last week or month -- and you know the name and location of the resource, and the date when it was last in good shape. You browse through a list of resources to find the one you want to restore.


== Restore KVM virtual machines

Restore KVM virtual machines using the Restore menu. You can search for the snapshot by its name or by using filters. 

*Required Console role*
Backup and Recovery super admin or Backup and Recovery restore admin role. https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html[Learn about NetApp Console access roles for all services^].

.Steps

. From the NetApp Console menu, select *Protection > Backup and Recovery*.
. From the NetApp Backup and Recovery menu, select *Restore*.

. From the drop-down list to the right of the name search field, select *KVM*. 

. Enter the name of the VM you want to restore or filter for VM host or storage pool where the resource that you want to restore is located. 
+
A list of snapshots appears that match your search criteria.

. Select the *Restore* button for the snapshot that you want to restore. 
+
A list of possible restore points appears.

. Select the restore point that you want to use.
. Select a snapshot source location.
. Select *Next* to continue.
. Choose the restore destination and settings:
+
[discrete]
===== Destination selection
+
[role="tabbed-block"]
====

.Restore to original location

--

.. Select the *Original location* pane.

.. In the *Post-restore options* section, enable the *Restart virtual machine* option to restart the VM after the restore operation completes.

.. Select *Restore*.

--

.Restore to alternate location

--
.. Select the *Alternate location* pane.
.. In the *Cloudstack settings*: section, provide the following information:
+
* *Zone*: Choose a destination CloudStack zone from the list. 
* *Pod*: Choose a destination pod within the selected zone from the list.
* *Cluster*: Choose a destination cluster within the selected pod from the list.
* *Host*: Choose a destination host in the cluster from the list.
* *Storage pool*: Choose a destination storage pool from the list (the destination volume should be located here).
* *Network*: Select the network to which the restored VM will be connected.
* *VM name*: Enter a name for the VM to be restored.
* *Display Name*: Enter the name that should be displayed for this VM in Backup and Recovery.
* *Storage Pool Path*: Enter the storage pool path where the VM volumes will be stored.

.. Choose a service offering that defines your preferred level of resource allocation from the *Select service offering* list.
.. Enable the *Forced* option to import the restored VM even if one or more of the VM's NIC MAC addresses are already present. If a MAC address already exists, a new MAC address is generated for that NIC.
.. In the *Post restore options* section, consider the following options:
+
* *Restart virtual machine*: Enable this option to boot the new virtual machine after it is restored.

--

====

. Select *Restore*.