---
sidebar: sidebar
permalink: br-use-vmware-restore-vmdks-from-backups.html
keywords:
summary: You can restore existing VMDKs, or deleted or detached VMDKs, from either a primary or secondary backup of traditional VMs or vVol VMs.
---

= Restore specific virtual disks from backups
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can restore existing virtual disks (VMDKs), or deleted or detached virtual disks, from either a primary or secondary backups of traditional VMs or vVol VMs. This enables you to restore only specific VM data or applications, so that you don't need to restore the entire VM and all of its associated virtual disks in situations where only specific data is affected. After the virtual disk is restored, it is attached to the VM and is ready to  use.

You can restore one or more virtual machine disks (VMDKs) on a VM to the same datastore or to different datastores.

[TIP]
For improved performance of restore operations in NFS environments, enable the VMware application vStorage API for Array Integration (VAAI).

.Before you begin

* A backup must exist.
* The VM must not be in transit.
+
The VM that you want to restore must not be in a state of vMotion or Storage vMotion.

.About this task

* If the VMDK is deleted or detached from the VM, then the restore operation attaches the VMDK to the VM.
* A restore operation might fail if the storage tier of the FabricPool where the VM is located is unavailable.
* Attach and restore operations connect VMDKs using the default SCSi controller. 
However, when VMDKs that are attached to a VM with a NVMe disk are backed up, the attach and restore operations use NVMe controller if available.

.Steps

. From the NetApp Backup and Recovery menu, select *Restore*.
. From the drop-down list to the right of the name search field, select *VMware*. 
. Enter the name of the resource you want to restore or filter for the vCenter, datacenter, or datastore where the resource that you want to restore is located. 
+
A list of virtual machines appears that match your search criteria.

. Find the VM that you want to restore from in the list, and select the *Restore virtual disks* button for that VM. 
+
A list of snapshots (restore points) created on that virtual machine appears.
. Enable the check box for the snapshot you want to restore.
. Select *Next*.
+
Snapshot location options appear.

. Select the restore destination for the snapshot:  
+
* *Local*: Restores the snapshot to the original location.
* *Secondary*: Restores the snapshot to a secondary storage location. 
+
If you choose secondary storage, enter the source and destination locations for both data and logs. 
* *Object store*: Restores the snapshot to an object storage location.  

. Select *Next* to continue to the Restore destination settings page.
. Choose the destination settings and pre- and post-restore options.

[discrete]
===== Destination selection

. Choose the destination settings and the pre-restore and post-restore options.

//Start tabbed area 

[role="tabbed-block"]
====

.Restore to original location
--
When restoring to the original location, you cannot change the destination vCenter, ESXi host, datastore, or name of the VM. The original VM is overwritten with the restore operation.
. Select the *Original location* pane.
. Enter the following information:
+
* *Pre-restore options* section:
** *Prescript*: Enable this option to automate additional tasks by running a custom script before the restore operation begins. Enter the full path for the script that should be run and any arguments that the script takes.
* *Post-restore options* section:
** *Restart virtual machine*: Enable this option to restart the virtual machine after the restore operation completes and after the post-restore script is applied.
** *Postscript*: Enable this option to automate additional tasks by running a custom script after the restore is complete. Enter the full path for the script that should be run and any arguments that the script takes.

. Select *Restore*.
--
.Restore to alternate location
--
When restoring to an alternate location, you can change the destination vCenter, ESXi host, datastore, and name of the VM to create a new copy of the VM in a different location or with a different name.
. Select the *Alternate location* pane.
. Enter the following information:
+
* *Destination settings* section:
** *vCenter FQDN or IP address*: Select the vCenter server where you want to restore the snapshot.
** *ESXi host*: Select the host where you want to restore the snapshot.
** *Network*: Select the network where you want to restore the snapshot.
** *Datastore*: Enter the name of the datastore where you want to restore the snapshot.
** *Virtual machine name*: Enter the name of the VM where you want to restore the snapshot. If the name matches a VM that already exists in the datastore, Backup and Recovery makes the name unique by appending a current timestamp.
* *Pre-restore options* section:
** *Prescript*: Enable this option to automate additional tasks by running a custom script before the restore operation begins. Enter the full path for the script that should be run and any arguments that the script takes.
* *Post-restore options* section:
** *Restart virtual machine*: Enable this option to restart the virtual machine after the restore operation completes and after the post-restore script is applied.
** *Postscript*: Enable this option to automate additional tasks by running a custom script after the restore is complete. Enter the full path for the script that should be run and any arguments that the script takes.

. Select *Restore*.
--

====


////
.Steps

. In the VMware vSphere client user interface, select *Menu* in the toolbar, and then select *VMs and Templates* from the drop-down list.
. In the left navigator pane, right-click a VM, then select *SnapCenter Plug-in for VMware vSphere* in the drop-down list, and then select *Restore* in the secondary drop-down list.
. In the *Restore* wizard, on the Select Backup page, select the backup copy that you want to restore from.
+
You can search for a specific backup name or a partial backup name, or you can filter the backup list by selecting the filter icon and selecting a date and time range, selecting whether you want backups that contain VMware snapshots, whether you want mounted backups, and primary or secondary location. Select *OK* to return to the wizard.

. On the *Select Scope* page, select the restore destination.
+
|===
|To restore to… |Specify the restore destination…

|The original datastore
|Select *Particular disk* from the drop-down list and then select *Next*.
In the Datastore selection table, you can select or unselect any VMDKs.
|An alternate datastore in an alternate location
|Select the destination datastore and select a different datastore from the list.
|===

. On the *Select Location* page, select the snapshot that you want to restore (primary or secondary).
. Review the Summary page and then select *Finish*.
. Optional: Monitor the operation progress by selecting *Recent Tasks* at the bottom of the screen.
. Refresh the screen to display updated information.

////


