---
sidebar: sidebar
permalink: br-use-mssql-protect-overview.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, on-premises, applications, virtual machines, backup and recovery
summary: Protect your Microsoft SQL Server application data from on-premises ONTAP systems to Amazon Web Services, Microsoft Azure, or StorageGRID using NetApp Backup and Recovery.
---

= Protect Microsoft SQL Server workloads with NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Back up Microsoft SQL Server databases from on-premises ONTAP systems to AWS, Azure, or StorageGRID using NetApp Backup and Recovery. Implement a 3-2-1 backup strategy with snapshots on primary storage, replication to secondary storage, and copies to object storage.

NetApp Backup and Recovery uses NetApp SnapMirror to synchronize backups by creating snapshots and transferring them to the backup locations.

Use the following workflows to protect your data: 

* link:concept-start-prereq-snapcenter-import.html[Configure additional items if importing from SnapCenter]
* link:br-start-discover.html[Discover Microsoft SQL Server workloads and optionally import SnapCenter resources]
* link:br-use-mssql-backup.html[Back up workloads with local snapshots on local ONTAP primary storage]
* link:br-use-mssql-backup.html[Replicate workloads to ONTAP secondary storage]
* link:br-use-mssql-backup.html[Back up workloads to an object store location] 
* link:br-use-mssql-backup.html[Back up workloads now]
* link:br-use-mssql-restore.html[Restore workloads]
* link:br-use-mssql-clone.html[Clone workloads]
* link:br-use-manage-inventory.html[Manage inventory of workloads]
* link:br-use-manage-snapshots.html[Manage snapshots]

To back up workloads, you create policies that manage backup and restore operations. See link:br-use-policies-create.html[Create policies] for more information.

.Supported backup destinations

NetApp Backup and Recovery supports backups of Microsoft SQL Server instances and databases from the following source systems to the listed secondary systems and object stores in public and private clouds. Snapshots remain on the source system.

[cols=3*,options="header",cols="33,33,33",width="90%"]
|===

| Source system
| Secondary system (replication)
| Destination object store (backup)

| Cloud Volumes ONTAP in AWS
| Cloud Volumes ONTAP in AWS
On-premises ONTAP system
| Amazon S3
ONTAP S3

| Cloud Volumes ONTAP in Azure
| Cloud Volumes ONTAP in Azure
On-premises ONTAP system
| Azure Blob
ONTAP S3

| On-premises ONTAP system | 
Cloud Volumes ONTAP 
On-premises ONTAP system  
|Amazon S3
Azure Blob
NetApp StorageGRID
ONTAP S3

| Amazon FSx for NetApp ONTAP 
| Amazon FSx for NetApp ONTAP 
| NA
|===

.Supported restore destinations

You can restore Microsoft SQL Server instances and databases from a backup that resides in primary storage, a secondary system (replicated volume), or object storage (backup file) to the following destination systems. Snapshots reside on the source system and can be restored only to that same system.

[cols=3*,options="header",cols="33,33,33",width="100%"]
|===

2+^| From backup file location
| To destination system

| *Object store (backup)* | *Secondary system (replication)* |

| Amazon S3 | Cloud Volumes ONTAP in AWS
On-premises ONTAP system |  Cloud Volumes ONTAP in AWS
On-premises ONTAP system
ONTAP S3

| Azure Blob | Cloud Volumes ONTAP in Azure
On-premises ONTAP system | Cloud Volumes ONTAP in Azure
On-premises ONTAP system 
ONTAP S3

| StorageGRID | Cloud Volumes ONTAP 
On-premises ONTAP system  | On-premises ONTAP system
ONTAP S3
|===

NOTE: References to "on-premises ONTAP systems" include FAS and AFF systems.


