---
sidebar: sidebar
permalink: br-use-vmware-configure-credentials-for-vm-guest-file-restores.html
keywords:
summary: 'When you attach a virtual disk for guest file or folder restore operations, the target VM for the attach must have credentials configured before you restore.'
---

= Configure credentials for VM guest file restores
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you attach a virtual disk for guest file or folder restore operations, the target VM for the attach must have credentials configured before you restore.

.About this task

The following table lists the credential requirements for guest restore operations.

|===
| |User access control enabled |User access control disabled

|Domain user
|You can use a domain user with "administrator" as the username. For example, "NetApp\administrator".
However, you cannot use a domain user with "xyz" as the username, even if the user belongs to a local administrator group. For example, you cannot use "NetApp\xyz".
|Either a domain user with "administrator" as the username or a domain user with "xyz" as the username that belongs to a local administrator group, works fine. For example, "NetApp\administrator" or "NetApp\xyz".
|Workgroup user
|A local user with "administrator" as the username works fine.
However, a local user with "xyz" as the username that belongs to a local administrator group will not work.
|Either a local user with "administrator" as the username or a local user with "xyz" as the username that belongs to a local administrator group, works fine.
However, a local user with "xyz" as the username that does not belong to local administrator group will not work.
|===

In the preceding examples, "NetApp" is the dummy domain name and "xyz" is the dummy local username

.Steps

. From the vSphere client shortcuts window, select *SnapCenter Plug-in for VMware vSphere* under plug-ins.
. In the left navigation select *Guest File Restore*.
. In the *Run As Credentials* section, do one of the following:
+
|===
|To do this… |Do this…

|Use existing credentials
|Select any of the configured credentials.
|Add new credentials
a|
. Select *Add*.
. In the *Run As Credentials* dialog box, enter the credentials.
Enter "Administrator" for *Username*.
. Select *Select VM*, then select a VM in the *Proxy VM* dialog box. Select *Save* to return to the *Run As Credentials* dialog box.
Select the VM that should be used to authenticate the credentials.
|===
+
NetApp Backup and Recovery uses the selected credentials to log on to the selected VM.

. Select *Save*.
