---
sidebar: sidebar
permalink: br-use-vmware-restore-guest-files-and-folders-overview.html
keywords:
summary: 'You can restore files or folders from a virtual machine disk (VMDK) on a Windows guest OS.'
---

= Requirements and limitations when restoring guest files and folders
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
You can restore files or folders from a virtual machine disk (VMDK) on a Windows guest OS.

== Guest restore workflow

Guest OS restore operations include the following steps:

. Attach
+
Attach a virtual disk to a guest VM or proxy VM and start a guest file restore session.

. Wait
+
Wait for the attach operation to complete before you can browse and restore. When the attach operation finishes, a guest file restore session is automatically created.

. Select files or folders
+
Browse the VMDK files and select one or more files or folders to restore.

. Restore
+
Restore the selected files or folders to a specified location.

== Prerequisites for restoring guest files and folders

Review all requirements before restoring files or folders from a VMDK on a Windows guest OS.

* VMware tools must be installed and running.
+
NetApp Backup and Recovery uses information from VMware tools to establish a connection to the VMware Guest OS.

* The Windows Guest OS must be running Windows Server 2008 R2 or later.
+
For the latest information about supported versions, refer to https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool (IMT)^].

* Credentials for the target VM use the built-in domain or local administrator account with the username "Administrator". Before starting the restore operation, configure the credentials for the VM where you want to attach the virtual disk. Credentials are required for both attach and restore operations. Workgroup users can use the built-in local administrator account.
+
[IMPORTANT]
If you must use an account that is not the built-in administrator account, but has administrative privileges within the VM, you must disable UAC on the guest VM.

* You must know the backup snapshot and VMDK to restore from.
+
NetApp Backup and Recovery does not support searching of files or folders to restore. Before you begin you must know where the files or folders are in the snapshot and the corresponding VMDK.

* Virtual disk to be attached must be in a NetApp Backup and Recovery backup.
+
The virtual disk that contains the file or folder you want to restore must be in a VM backup that was performed using NetApp Backup and Recovery.

//* To use a proxy VM, the proxy VM must be configured.
//+
//If you want to attach a virtual disk to a proxy VM, the proxy VM must be configured before the attach and restore operation begins.

* For files with non-English-alphabet names, you must restore them in a directory, not as a single file.
+
You can restore files with non-alphabetic names, such as Japanese Kanji, by restoring the directory in which the files are located.

== Guest file restore limitations

Before you restore a file or folder from a guest OS, you should be aware of the feature limitations.

* You cannot restore dynamic disk types inside a guest OS.
* If you restore an encrypted file or folder, the encryption attribute is not retained. You cannot restore files or folders to an encrypted folder.
* The Guest File Browse page displays the hidden files and folder, which you cannot filter.
* You cannot restore from a Linux guest OS.
+
You cannot restore files and folders from a VM that is running Linux guest OS. However, you can attach a VMDK and then manually restore the files and folders. For the latest information on supported guest OS, refer to the https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT[NetApp Interoperability Matrix Tool (IMT)^].

* You cannot restore from a NTFS file system to a FAT file system.
+
When you try to restore from NTFS-format to FAT-format, the NTFS security descriptor is not copied because the FAT file system does not support Windows security attributes.

* You cannot restore guest files from a cloned VMDK or an uninitialized VMDK.
* You cannot restore the directory structure for a file.
+
When you restore a file from a nested directory, the system restores only the file, not its directory structure. To restore the entire directory tree, copy the top-level directory.

* You cannot restore guest files from a vVol VM to an alternate host.

* You cannot restore encrypted guest files.
