---
sidebar: sidebar
permalink: concept-start-prereq.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery
summary: Get started with NetApp Backup and Recovery by verifying the readiness of your operational environment, Console agent, and Console account. To use NetApp Backup and Recovery, you'll need these prerequisites.
---
= NetApp Backup and Recovery requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/
:table-caption!:

[.lead]
Before you begin using NetApp Backup and Recovery, ensure your NetApp Console and operational environment meet the following requirements.

== Prepare NetApp Console
You access NetApp Backup and Recovery through NetApp Console. To prepare the Console for Backup and Recovery, you must:

* Add a Console agent
* Add at least one storage system
* Configure a Console organization and user roles

You need the Organization admin or Super admin role in NetApp Console to complete this preparation. 

To learn more about NetApp Console, refer to https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html[NetApp Console for unified storage management^].

=== Complete initial NetApp Console setup
Complete the initial setup for NetApp Console if you haven't already.

https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html[Getting started workflow for NetApp Console (SaaS application)^]

=== Deploy a Console agent
A Console agent is a lightweight software component that you install in your network to connect your storage infrastructure to NetApp Console. It enables advanced storage orchestration, data services, and secure cloud integration.

https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html[Learn about Console agents^]
https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html[Deploy a Console agent^]
 
=== Add a storage system
Before you can protect workloads in Backup and Recovery, you need to add an ONTAP storage system to the Console. 

https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters in NetApp Console^]

=== Configure an organization and user roles
Learn about organizations, projects, and user roles, then configure users with the appropriate permissions needed to perform their tasks.

Refer to https://docs.netapp.com/us-en/console-setup-admin/task-iam-manage-members-permissions.html[Add users to a NetApp Console organization] for information about using an organization and projects for controlling resource access.

Refer to https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html[NetApp Backup and Recovery roles in NetApp Console] for details about the roles and permissions needed to perform operations in NetApp Backup and Recovery.

== Requirements for backups to object storage

To use object storage as backup targets, you need an account with AWS S3, Google Cloud Storage, Microsoft Azure Blob, StorageGRID, or ONTAP and the appropriate access permissions configured.


== Requirements for protecting ONTAP volume workloads
To use NetApp Backup and Recovery for ONTAP volume workloads, you need the following host system, space, and sizing prerequisites.

* ONTAP 9.8 or later is required.
* ONTAP 9.12.1 or later is required for FlexGroup volume protection. Refer to link:br-reference-limitations.html[Known limitations with NetApp Backup and Recovery for ONTAP volumes] for more information.
* ONTAP 9.17.1 or later is required for backing up or restoring to S3-compatible object storage.
* An ONTAP One License must be enabled on the on-premises ONTAP instance.

For information about supported features, volume types, backup and restore destinations, and more, refer to link:prev-ontap-protect-overview.html[Protect your ONTAP volume data].


== Requirements for protecting Microsoft SQL Server workloads 

To use NetApp Backup and Recovery for Microsoft SQL Server workloads, you need the following host system, space, and sizing prerequisites.

[caption=]
.Software and hardware requirements
[cols=2*,options="header",cols="33,66a",width="90%"]
|===

| Item
| Requirements

| Operating systems
| Microsoft Windows
For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome[NetApp Interoperability Matrix Tool^].
| Microsoft SQL Server versions | Version 2012 and later are supported for VMware Virtual Machine File System (VMFS) and VMware Virtual Machine Disk (VMDK) NFS.

| SnapCenter Server version | SnapCenter Server version 5.0 or greater is required if you are going to import your existing data from SnapCenter into NetApp Backup and Recovery.

NOTE: If you already have SnapCenter, first check to be sure you've met the prerequisites before importing from SnapCenter. See link:concept-start-prereq-snapcenter-import.html[Prerequisites for importing resources from SnapCenter].

| Minimum RAM for the plug-in on the SQL Server host
| 1 GB

| Minimum install and log space for the plug-in on the SQL Server host
| 5 GB

Allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of backups performed and the frequency of data protection operations. If there is not sufficient space, the logs will not be created for the operations. 

|Required software packages
| * ASP.NET Core Runtime 8.0.24 Hosting Bundle (and all subsequent 8.0.x patches)
* PowerShell 7.4.13

For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome[NetApp Interoperability Matrix Tool^].

|===

[caption=]
.Supported storage types
[cols=2*,options="header",cols="33,66a",width="90%"]
|===

| Database host
| Supported storage

| Physical server
a|

* LUNs presented over Fibre Channel
* LUNs presented over iSCSI

| VMware VM
a|
* iSCSI LUNs connected directly to the guest system by the iSCSI initiator
* Virtual Machine File Systems (VMFS)
* NFS datastores

| Hyper-V VM
a|iSCSI LUNs connected directly to the guest system by the iSCSI initiator

NOTE: Protecting databases stored in pass-through disks or VHD/VHDX files that are provisioned on NetApp storage is not supported.

|===

== Requirements for protecting VMware workloads
You need specific requirements to discover and protect your VMware workloads.

[caption=]
.Software support
[options="header"]
|===
|Requirement |Supported

|Datastore types
|NFSv3, NFSv4.1, and VMFS

|VMware ESXi Server versions
|7.0U1 and above

|VMware vCenter vSphere versions
|7.0U1 and above

|VMware Tools
|VMWare Tools is required when using the file and folder restore feature and VM-consistent backups. To make sure the VMware Tools version matches your version of ESXi Server, refer to the https://packages.vmware.com/tools/versions[VMware version mapping information].

|IP address types
|IPv4, IPv6

|VMware TLS versions
|1.2, 1.3

|Connected storage
a|
* ONTAP 9.13.1 or later
* Amazon FSx for NetApp ONTAP storage systems running version 9.13.1 or later
* ASA r2 SAN-only systems (ONTAP 9.17.1 or later required)
|===

[caption=]
.Connection and port requirements for protecting VMware workloads
[cols=2*,options="header",cols="33,66a",width="90%"]
|===

| Type of port
| Pre-configured port

| VMware ESXi Server port | 443 (HTTPS), bidirectional. The file and folder restore feature uses this port. 

| Storage cluster or storage VM port 
a| 
* 443 (HTTPS), bidirectional. 
* 80 (HTTP), bidirectional. This port is used for communication between the virtual appliance and the storage VM or the cluster containing the storage VM. 
|===

.Role-based access control (RBAC) requirements for protecting VMware workloads

Your Console user account needs to have the Backup and Recovery super admin role to work with VMware workloads.

For more information about Backup and Recovery roles, refer to https://docs.netapp.com/us-en/console-setup-admin/reference-iam-backup-rec-roles.html[Backup and Recovery roles in NetApp Console].


// The vCenter administrator account must have the required vCenter privileges. 

// For a list of vCenter privileges needed, see https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deployment_planning_and_requirements.html#rbac-privileges-required[SnapCenter Plug-in for VMware vSphere vCenter privileges needed^].

== Requirements for protecting KVM workloads
You need specific requirements to discover and protect KVM virtual machines.

* A modern Linux distribution running kernel version 5.14.0-503.22.1.el9_5.x86_64 (longterm) or later
* Your KVM hosts and VMs must be managed by a management platform. NetApp Backup and Recovery supports the following management platforms:
** Apache CloudStack 4.22.0.0
* Ensure that inbound network traffic to port 22 is allowed from the Console agent to the KVM host
* QEMU Guest Agent version 9.0.0 or later
* libvirt version 10.5.0 or later

NOTE: To ensure that KVM workload restores complete successfully, make sure that the *Enable VM-consistent snapshot* setting is active in the protection policy you use for KVM backups.

[NOTE]
=====
To enable protection of KVM VMs administered by non-root users, use the following steps:

. Mount the volume as type NFS3 to avoid the use of the `nobody` user and group.
. Use the following command to add a non-root user to the `qemu` group wile preserving their existing groups:
+
[source,console]
----
usermod -aG qemu <non-root-user>
----
. Use the following command to grant ownership of the mount path to the `qemu` user and group and change permissions for the mount path:
+
[source,console]
----
chown -R qemu:qemu <kvm_vm_mount_path> & chmod 771 <kvm_vm_mount_path>
----
. Delete the existing NetApp_SnapCenter_Backups directory if present.
=====

== Requirements for protecting Oracle Database workloads
Ensure your environment meets specific requirements to discover and protect Oracle Database resources.

[options="header"]
|===
|Requirement |Supported

|Deployment topology
a|
* Standalone (NFS, SAN, ASM SAN)
* RAC over ASM (VMDK on VMFS)

|Oracle Database versions
a|
* Oracle Database 19c
* Oracle Database 21c
* Oracle AI Database 26ai

|Database storage
|Must be deployed on NetApp ONTAP (primary or secondary)

|Host OS
a|
* Red Hat Enterprise Linux 8
* Red Hat Enterprise Linux 9

|Object storage (backup targets)
a|
* Azure Object Storage
* Amazon AWS
* NetApp StorageGRID
* ONTAP S3

|===

== Requirements for protecting Kubernetes applications
You need specific requirements to discover Kubernetes resources and protect your Kubernetes applications.

For NetApp Console requirements, refer to <<Prepare NetApp Console>>.

NOTE: NetApp strongly recommends assigning a static IP address to the Console agent you use for Kubernetes workloads to avoid issues if the agent IP address changes.

* A primary ONTAP system (ASA r2 systems are not supported)
* NetApp Trident 25.02 or later
* NetApp Trident Protect 26.05 or later (installed on the Kubernetes cluster during discovery)
//* NetApp Trident Protect Connector 26.05 or later (installed during Kubernetes workload discovery)
* A Kubernetes cluster - Supported Kubernetes distributions and versions include those supported by https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-requirements.html[Trident Protect].
** Make sure that TCP port 443 is unfiltered in the outbound direction between the Kubernetes cluster, the Trident Protect Connector, and the Trident Protect proxy.

== Requirements for protecting Hyper-V workloads
Ensure your Hyper-V instance meets specific requirements to discover and protect virtual machines.

[caption=]
.Software requirements for the Hyper-V Windows Server host
[options="header"]
|===
|Requirement |Supported

|Microsoft Hyper-V
|2019, 2022 & 2025 editions

|ASP.NET Core Runtime
|8.0.24 Hosting Bundle (and all subsequent 8.0.x patches)

|PowerShell
|7.4.13 or later

|If non-administrator users will be protecting Hyper-V VMs, ensure the users have the following permissions
a|
* Member of the local administrators group
* Part of the "Log on as service" local security policy

|Ensure that two-way HTTPS traffic is allowed for the following ports in the Windows Firewall settings
a|
* TCP 8144 (NetApp Plugin for Hyper-V)
* TCP 8145 (NetApp Plugin for Windows)

|Connected storage
a|
* ONTAP 9.13.1 or later
* SMB shares
* SAN storage connected via iSCSI or Fibre Channel
|===

// snapcenter GH issue #230, 2026-MAR-24

.Hardware requirements for the Hyper-V host

* Standalone and FCI-clustered hosts are supported
* 1GB RAM minimum for the NetApp Hyper-V plug-in on the Hyper-V host
* 5GB minimum installation and log space for the plug-in on the Hyper-V Host
+
NOTE: Ensure that you allocate enough disk space on the Hyper-V host for the logs folder and regularly monitor its usage. The required space depends on how often backups and data protection operations occur. If there isn't enough space, logs will not be generated.

.NetApp ONTAP configuration requirements

* A primary ONTAP system (ONTAP 9.14.1 or later)
* For Hyper-V deployments using SMB shares to store virtual machine data, ensure that the continuous availability share property is enabled on the ONTAP system. Refer to the https://docs.netapp.com/us-en/ontap/smb-hyper-v-sql/configure-shares-continuous-availability-task.html[ONTAP documentation^] for instructions.