---
sidebar: sidebar
permalink: prev-vmware-register-snapcenter.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: Protect your VMware workloads with NetApp NetApp Backup and Recovery. 
---

= Register SnapCenter Plug-in for VMware vSphere host to use with NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You should register the SnapCenter Plug-in for VMware vSphere host in NetApp Backup and Recovery for the datastores and virtual machines to be displayed. Only a user with administrative access can register the SnapCenter Plug-in for VMware vSphere host.

NOTE: To switch to and from NetApp Backup and Recovery workloads, refer to link:br-start-switch-ui.html[Switch to different NetApp Backup and Recovery workloads].



.Steps

. In the NetApp Console UI, select *Protection* > *Backup and Recovery* > *Virtual Machines*.
. From the *Settings* drop-down, select *SnapCenter Plug-in for VMware vSphere*.
. Select *Register SnapCenter Plug-in for VMware vSphere*.
. Specify the following details:
.. In the SnapCenter Plug-in for VMware vSphere field, specify the FQDN or IP address of the SnapCenter Plug-in for VMware vSphere host.
.. In the Port field, specify the port number on which the SnapCenter Plug-in for VMware vSphere host is running.
+
You should ensure that communication is open between on-premises SnapCenter Plug-in for VMware vSphere host which is running on the default 8144 port and Console agent instance which could be either running in any cloud providers (Amazon Web Services, Microsoft Azure, Google Cloud Platform) or on-premises.
.. In the Username and Password field, specify the credentials of the vCenter user with the administrator role.
. Select *Register*.

*After you finish*

Select *Backup and Recovery* > *Virtual Machines* to view all the datastores and virtual machines that are protected using the registered SnapCenter Plug-in for VMware vSphere host.
