---
sidebar: sidebar
permalink: prev-ontap-backup-onprem-s3-compatible.html
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, NetApp Backup and Recovery, S3, compatible, Oracle database, Microsoft SQL Server database, SAP HANA database
summary: Protect your VMware workloads with NetApp Backup and Recovery. 
---

= Back up on-premises ONTAP data to S3-compatible storage with NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Complete a few steps in NetApp Backup and Recovery to get started backing up volume data from your primary on-premises ONTAP systems. You can send backups to a secondary ONTAP storage system (a replicated volume) or to a bucket on an S3-compatible storage system, or both.

== Verify support for your configuration

Read the following requirements to make sure that you have a supported configuration before you start backing up volumes to S3-compatible storage.

Supported ONTAP versions::
A minimum ONTAP version of 9.17.1 is required.

=== Supported actions
The following are supported actions when backing up to S3-compatible storage:

* Backup of crash-consistent and app-consistent snapshots from on-premises ONTAP to third-party S3-compatible object stores
* Core data protection workflows: backup, restore, and backup deletion
* Tested and validated with Wasabi object storage; customers have also reported successful deployments with MinIO and IBM Cloud Object Storage
* NetApp Support accepts and triages all support requests involving third-party S3-compatible object stores

=== Unsupported features and configurations
The following features and configurations are not supported when backing up to S3-compatible storage:

* Bring Your Own Bucket (BYOB) is not supported
* DataLock enablement in backup policies is not supported
* Archival mode enablement in backup policies is not supported
* Bucket-level encryption options are not supported
* MetroCluster configurations are not supported
* Cloud-based ONTAP environments are not supported — only on-premises ONTAP is supported

=== Caveats
Keep in mind the following points when backing up to S3-compatible storage:

* *Performance is not guaranteed*: NetApp products are sensitive to S3 API latency and IOPS. Third-party object stores must provide AWS S3-equivalent latency and IOPS to achieve comparable performance. NetApp does not troubleshoot object store performance.
* *No liability for data corruption or loss*: NetApp is not responsible for data loss or service downtime caused by issues with third-party S3 object stores.
* *Limited feature support*: The supported feature set for third-party S3-compatible targets is a subset of what is available for native targets (AWS S3, Azure Blob, GCP, ONTAP S3, StorageGRID).

//NOTE: To switch to and from NetApp Backup and Recovery workloads, refer to link:br-start-switch-ui.html[Switch to different NetApp Backup and Recovery workloads].

== Prepare your Console agent

The Console agent is the main software for Console functionality. A Console agent is required to back up and restore your ONTAP data.

=== Create or switch Console agents

When you back up data to S3-compatible storage, a Console agent must be available on your premises or in the cloud. You'll either need to install a new Console agent or make sure that the currently selected Console agent resides in one of these locations. The on-premises Console agent can be installed in a site with or without internet access.

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html[Learn about Console agents^]
* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html#how-to-create-a-connector[Install the Console agent in your cloud environment^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-connector-on-prem.html[Installing the Console agent on a Linux host with internet access^]
* https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-private-mode.html[Installing the Console agent on a Linux host without internet access^]
* https://docs.netapp.com/us-en/console-setup-admin/task-manage-multiple-connectors.html#switch-between-connectors[Switching between Console agents^]

=== Prepare Console agent networking requirements

Ensure that the network where the Console agent is installed enables the following connections:

* An HTTPS connection over port 443 to the S3-compatible server
* An HTTPS connection over port 443 to your source ONTAP cluster management LIF
* An outbound internet connection over port 443 to NetApp Backup and Recovery (not required when the Console agent is installed in a "dark" site)

==== Private mode (dark site) considerations

NetApp Backup and Recovery functionality is built into the Console agent. When it is installed in private mode, you'll need to update the Console agent software periodically to get access to new features. Check the link:whats-new.html[NetApp Backup and Recovery What's New] to see the new features in each NetApp Backup and Recovery release. When you want to use the new features, follow the steps to https://docs.netapp.com/us-en/console-setup-admin/task-upgrade-connector.html[upgrade the Console agent software^].

When you use NetApp Backup and Recovery in a standard SaaS environment, the NetApp Backup and Recovery configuration data is backed up to the cloud. When you use NetApp Backup and Recovery in a site with no internet access, the NetApp Backup and Recovery configuration data is backed up to the S3-compatible bucket where your backups are being stored. 

== Verify license requirements 

Before you can activate NetApp Backup and Recovery for your cluster, you'll need to purchase and activate a NetApp Backup and Recovery BYOL license from NetApp. The license is for backup and restore to object storage - no license is needed to create snapshots or replicated volumes. This license is for the account and can be used across multiple systems.

You'll need the serial number from NetApp that enables you to use the service for the duration and capacity of the license. link:br-start-licensing.html[Learn how to manage your BYOL licenses].

TIP: PAYGO licensing is not supported when backing up files to S3-compatible storage.

== Prepare your ONTAP clusters

// This section uses an include along with the 2 subsections of "Discover your ONTAP cluster in BlueXP" and "Verify ONTAP requirements"

include::../_include/backup-onprem-prepare-onprem-ONTAP-cluster.adoc[]

// === Discover your ONTAP systems in BlueXP
// FROM INCLUDE

// === Verify ONTAP system requirements
// FROM INCLUDE

=== Verify ONTAP networking requirements for backing up data to object storage

You must ensure that the following requirements are met on the system that connects to object storage. 

[NOTE]
====
* When you use a fan-out backup architecture, the settings must be configured on the _primary_ storage system. 
* When you use a cascaded backup architecture, the settings must be configured on the _secondary_ storage system.
+
link:prev-ontap-protect-journey.html[Learn more about the types of backup architecture].
====

The following ONTAP cluster networking requirements are needed: 

* The ONTAP cluster initiates an HTTPS connection over a user-specified port from the intercluster LIF to the S3-compatible server for backup and restore operations. The port is configurable during backup setup.
+
ONTAP reads and writes data to and from object storage. The object storage never initiates, it just responds.
+
* ONTAP requires an inbound connection from the Console agent to the cluster management LIF.

* An intercluster LIF is required on each ONTAP node that hosts the volumes you want to back up. The LIF must be associated with the _IPspace_ that ONTAP should use to connect to object storage. https://docs.netapp.com/us-en/ontap/networking/standard_properties_of_ipspaces.html[Learn more about IPspaces^].
+
When you set up NetApp Backup and Recovery, you are prompted for the IPspace to use. You should choose the IPspace that each LIF is associated with. That might be the "Default" IPspace or a custom IPspace that you created.
* The nodes' intercluster LIFs are able to access the object store (not required when the Console agent is installed in a "dark" site).
* DNS servers have been configured for the storage VM where the volumes are located. See how to https://docs.netapp.com/us-en/ontap/networking/configure_dns_services_auto.html[configure DNS services for the SVM^].
* If you are using a different IPspace than Default, then you might need to create a static route to get access to the object storage.
* Update firewall rules, if necessary, to allow NetApp Backup and Recovery service connections from ONTAP to object storage through the port you specified (typically port 443) and name resolution traffic from the storage VM to the DNS server over port 53 (TCP/UDP).

===  Verify ONTAP networking requirements for replicating volumes

If you plan to create replicated volumes on a secondary ONTAP system using NetApp Backup and Recovery, make sure that the source and destination systems meet the following networking requirements.

* If the cluster is on-premises, you should have a connection from your corporate network to your virtual network in the cloud provider. This is typically a VPN connection.
* ONTAP clusters must meet additional subnet, port, firewall, and cluster requirements.

== Activate backups on your ONTAP volumes

Activate backups at any time directly from your on-premises system.

A wizard takes you through the following major steps: 

* Select the volumes that you want to back up
* Define the backup strategy and policies
* Review your selections 

You can also <<Show the API commands>> at the review step, so you can copy the code to automate backup activation for future systems.  

=== Start the wizard 

.Steps 

. Access the Activate backup and recovery wizard using one of the following ways: 
* From the Console *Systems* page, select the system and select *Enable > Backup Volumes* next to Backup and Recovery in the right-panel.
//+
//If the destination for your backups exists as a system on the Canvas, you can drag the ONTAP cluster onto the object storage. 
* Select *Volumes* in the Backup and recovery bar. From the Volumes tab, select the *Actions (...)* option and select *Activate Backup* for a single volume (that does not already have replication or backup to object storage enabled). 

+ 
The Introduction page of the wizard shows the protection options including local snapshots, replications, and backups. If you did the second option in this step, the Define Backup Strategy page appears with one volume selected. 

. Continue with the following options: 

* If you already have a Console agent, you're all set. Just select *Next*. 
* If you don't have a Console agent, the *Add a Console agent* option appears. Refer to <<Prepare your Console agent>>. 

=== Select the volumes that you want to back up

Choose the volumes you want to protect. A protected volume is one that has one or more of the following: snapshot policy, replication policy, backup to object policy. 

You can choose to protect FlexVol or FlexGroup volumes; however, you cannot select a mix of these volumes when activating backup for a system. See how to link:prev-ontap-backup-manage.html[activate backup for additional volumes in the system] (FlexVol or FlexGroup) after you have configured backup for the initial volumes.

[NOTE] 
====
* You can activate a backup only on a single FlexGroup volume at a time. 
* When selecting source volumes that you want to protect, you can only select volumes that have matching SnapLock settings. The volumes you select must either all have the SnapLock feature enabled or all have the SnapLock feature disabled. 
====

.Steps 

Note that if the volumes you choose already have Snapshot or replication policies applied, then the policies you select later will overwrite these existing policies. 

. In the Select Volumes page, select the volume or volumes you want to protect. 
+
* Optionally, filter the rows to show only volumes with certain volume types, styles, and more to make the selection easier. 
* After you select the first volume, then you can select all FlexVol volumes (FlexGroup volumes can be selected one at a time only). To back up all existing FlexVol volumes, check one volume first and then check the box in the title row. 
* To back up individual volumes, check the box for each volume.

. Select *Next*.

=== Define the backup strategy 

Defining the backup strategy involves configuring the following options: 

* Protection options: Whether you want to implement one or all of the backup options: local snapshots, replication, and backup to object storage
* Architecture: Whether you want to use a fan-out or cascading backup architecture
* Local snapshot policy
* Replication target and policy
//+
//NOTE: If the volumes you choose have different Snapshot and replication policies than the policies you select in this step, the existing policies will be overwritten. 
* Backup to object storage information (provider, encryption, networking, backup policy, and export options). 

.Steps 

. In the Define Backup Strategy page, choose one or all of the following. All three are selected by default: 
+
* *Local Snapshots*: Creates local snapshots. 
* *Replication*: Creates replicated volumes on another ONTAP storage system.  
* *Backup*: Backs up volumes to a bucket on an ONTAP system configured for S3.  

. *Architecture*: If you chose both replication and backup, choose one of the following flows of information: 
* *Cascading*: Backup data flows from the primary to the secondary system, and then from the secondary to object storage. 
* *Fan out*: Backup data flows from the primary to the secondary system _and_ from the primary to object storage. 
+ 
For details about these architectures, refer to link:prev-ontap-protect-journey.html[Plan your protection journey].  

. *Local Snapshot*: Choose an existing snapshot policy or create a new one. 
+
TIP: If you want to create a custom policy before activating the Snapshot, you can use System Manager or the ONTAP CLI `snapmirror policy create` command. Refer to https://docs.netapp.com/us-en/ontap-cli-9131/snapmirror-policy-create.html[ONTAP CLI for `snapmirror policy`^].
+
TIP: To create a custom policy using Backup and Recovery, refer to link:br-use-policies-create.html[Create a policy].
+
To create a policy, select *Create new policy* and do the following: 

* Enter the name of the policy. 
* Select up to five schedules, typically of different frequencies. 
* Select *Create*. 

. *Replication*: If you selected *Replication*, set the following options: 
+
* *Replication target*: Select the destination system and Storage VM. Optionally, select the destination aggregate (or aggregates for FlexGroup volumes) and a prefix or suffix that will be added to the replicated volume name.

* *Replication policy*: Choose an existing replication policy or create a new one. 
+
To create a policy, select *Create new policy* and do the following: 
+
** Enter the name of the policy. 
** Select up to five schedules, typically of different frequencies. 
** Select *Create*. 

. *Back up to Object*: If you selected *Backup*, set the following options: 
+
* *Provider*: Select *ONTAP S3*. 
* *Provider settings*: Enter the S3 server FQDN details, port, and the users' access key and secret key.
+
The access key and secret key are for the user you created to give the ONTAP cluster access to the S3 bucket.

* *Networking*: Choose the IPspace in the source ONTAP cluster where the volumes you want to back up reside. The intercluster LIFs for this IPspace must have outbound internet access (not required when the Console agent is installed in a "dark" site).
+
TIP: Selecting the correct IPspace ensures that NetApp Backup and Recovery can set up a connection from ONTAP to your ONTAP S3 object storage.

* *Backup policy*: Select an existing backup policy or create a new one. 
+
TIP: You can create a policy with System Manager or the ONTAP CLI. To create a custom policy using the ONTAP CLI `snapmirror policy create` command, refer to https://docs.netapp.com/us-en/ontap-cli-9131/snapmirror-policy-create.html[ONTAP CLI for `snapmirror policy`^].
+
TIP: To create a custom policy using Backup and Recovery, refer to link:br-use-policies-create.html[Create a policy].
+
To create a policy, select *Create new policy* and do the following: 
+
** Enter the name of the policy. 
** Select up to five schedules, typically of different frequencies. 
** For backup-to-object policies, set the Datalock and Ransomware protection settings. For details on Datalock and Ransomware protection, refer to link:prev-ontap-policy-object-options.html[Backup-to-object policy settings].
** Select *Create*. 

+
* *Export existing snapshots to object storage as backup files*: If there are any local snapshots for volumes in this system that match the backup schedule label you just selected (for example, daily, weekly, etc.), this additional prompt is displayed. Check this box to have all historic Snapshots copied to object storage as backup files to ensure the most complete protection for your volumes.

. Select *Next*. 

=== Review your selections 

This is the chance to review your selections and make adjustments, if necessary. 

.Steps 

. In the Review page, review your selections. 
. Optionally check the box to *Automatically synchronize the Snapshot policy labels with the replication and backup policy labels*. This creates Snapshots with a label that matches the labels in the replication and backup policies. If the policies don't match, backups will not be created.
. Select *Activate Backup*. 

.Result 

NetApp Backup and Recovery starts taking the initial backups of your volumes. The baseline transfer of the replicated volume and the backup file includes a full copy of the source data. Subsequent transfers contain differential copies of the primary storage data contained in snapshots.

A replicated volume is created in the destination cluster that will be synchronized with the primary storage volume. 

An S3 bucket is created in the service account indicated by the S3 access key and secret key you entered, and the backup files are stored there.

The Volume Backup Dashboard is displayed so you can monitor the state of the backups.

You can also monitor the status of backup and restore jobs using the link:br-use-monitor-tasks.html[Job Monitoring page].

=== Show the API commands 

You might want to display and optionally copy the API commands used in the Activate backup and recovery wizard. You might want to do this to automate backup activation in future systems. 

.Steps 

. From the Activate backup and recovery wizard, select *View API request*. 
. To copy the commands to the clipboard, select the *Copy* icon. 


