---
sidebar: sidebar
permalink: reference-roles.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, roles, permissions, access control, role-based access control, rbac
summary: NetApp Backup and Recovery employs roles to govern the access that each user has to specific features and actions
---

= NetApp Backup and Recovery Identity and Access Management (IAM) roles  
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Backup and Recovery employs Identity and Access Management (IAM) to govern the access that each user has to specific features and actions.

The service uses the following roles that are specific to NetApp Backup and Recovery. 

* *Backup and Recovery super admin*: Perform any actions in NetApp Backup and Recovery.
* *Backup admin*: Perform backups to local snapshots, replicate to secondary storage, and back up to object storage actions in NetApp Backup and Recovery. 
* *Restore admin*: Restore workloads using NetApp Backup and Recovery. 
* *Clone admin*: Clone applications and data using NetApp Backup and Recovery. 
* *Backup and Recovery viewer*: View information in NetApp Backup and Recovery, but not perform any actions.




For details about all NetApp Console access roles, see https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[the NetApp Console setup and administration documentation^].

The following table indicates the actions that each NetApp Backup and Recovery role can perform. 

[cols=6*,options="header",cols="20,20,15,15a,15a,15a",width="100%"]
|===
| Feature and action
| Backup and Recovery super admin
| Backup admin
| Restore admin
| Clone admin
| Viewer

|Add, edit, or delete hosts | Yes | No | No | No | No
|Install plugins | Yes | No | No | No | No
|Add credentials (host, instance, vCenter) | Yes | No | No | No | No

| View dashboard and all tabs | Yes | Yes |Yes |Yes | Yes
| Start free trial | Yes | No  |No |No | No
| Initiate discovery of workloads | No | Yes |Yes |Yes | No
| View license information | Yes | Yes |Yes |Yes | Yes
| Activate license | Yes | No  |No |No | No
| View hosts | Yes | Yes |Yes |Yes | Yes

6+| *Schedules*: 
| Activate schedules | Yes | Yes |Yes |Yes | No
| Suspend schedules | Yes | Yes | Yes |Yes | No


6+| *Policies and protection*: 
| View protection plans | Yes | Yes  |Yes |Yes | Yes
| Create, modify, or delete protection | Yes | Yes  |No |No | No
| Restore workloads | Yes | No  |Yes |No | No
| Create clone, split clone, or delete clone | Yes | No  |No |Yes | No
| Create, modify, or delete policy | Yes | Yes  |No |No | No


6+| *Reports*: 
| View reports | Yes | Yes |Yes |Yes | Yes
| Create reports | Yes | Yes |Yes | Yes | No
| Delete reports | Yes | No |No | No | No


6+| *Import from SnapCenter and manage host*: 
| View imported SnapCenter data | Yes | Yes  |Yes |Yes | Yes
| Import data from SnapCenter| Yes | Yes | No | No | No
| Manage (migrate) host| Yes | Yes | No | No | No

6+| *Configure settings*:
| Configure log directory| Yes | Yes  |Yes |No | No
| Associate or remove instance credentials| Yes | Yes |Yes |No | No

6+| *Buckets*:
| View buckets| Yes | Yes  |Yes |Yes | Yes
| Create, edit, or delete bucket| Yes | Yes |No |No | No


|===
