---
sidebar: sidebar
permalink: task-preview-enable.html
keywords: cloud backup, NetApp Backup and Recovery, backup, restore, preview, enable, object storage, third-party, MinIO, S3-compatible
summary: You can monitor the status of local Snapshots, replications, and backup to object storage jobs that you initiated or that were scheduled, and restore jobs that you initiated or scheduled. You can see the jobs that have completed, are in progress, or failed so you can diagnose and fix problems. Using the Notification Center, you can enable notifications to be sent by email so you can be informed of important system activity even when you're not logged into the system. Using the Timeline, you can see details of all actions initiated via the UI or API.
---

= Enable preview features in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp Backup and Recovery offers preview features that enable you to test new capabilities before they are fully released. These features are designed to enhance your backup and recovery experience, but they may not be fully supported or stable.

IMPORTANT: These features are in preview mode and should not be used in production environments. They are intended for testing and feedback purposes only.

== Enable preview features
To enable preview features in NetApp Backup and Recovery, you need to set a flag on the Console agent. This flag lets you to access and test the preview features available in the service.

.Steps
. Log in to the Console agent.
. Switch to the Superuser. Run the command: 
+
`sudo su`

. List Docker volumes and identify the CBS volume. Run the command: 
+
----
podman volume ls | grep cbs
----

+
Expected output: 
+
----
local service-manager-2_cloudmanager_cbs_volume
----
. Inspect the volume to get the mountpoint. Run the command:
+
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
. Run the command:
+
----
podman volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Expected output: 
+
----
Mountpoint: 
/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----

. Navigate to the Docker Volumes directory. Change directory to the mountpoint obtained in the previous step:
+
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data/cbs_config

----

. Locate and edit the `production-customer.json` file.

. Ensure you are in the correct directory and the `production-customer.json` file is present.

. Open the `production-customer.json` file in your preferred text editor and add the following JSON snippet, ensuring the JSON structure is properly maintained:
+
----
{
   "feature-flags":
    {
        "volumes-dashboard-v2": true
     }
}
----

. Save the changes to the file.
. Restart NetApp Backup and Recovery Cloud Manager CBS Service. Run the command: 
+
----
podman restart cloudmanager_cbs
----


