---
sidebar: sidebar
permalink: task-setup-ca-certificates.html
keywords: cloud backup, backup and recovery, backup, restore, certificates, protection, security, storagegrid, backup, back up
summary: Create a security certificate to enable communication between NetApp Backup and Recovery and StorageGRID or ONTAP. 
---

= Set up CA certificates for NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Set up CA certificates so NetApp Backup and Recovery can validate secure connections to StorageGRID or ONTAP. Follow the steps that apply to your environment and the systems you want to protect.

== Create a CA certificate for StorageGRID

If communication between the NetApp Backup and Recovery containers and StorageGRID should verify the StorageGRID certificate, complete the following steps.

The generated certificate should use the same common name (CN) and Subject Alternative Name that you provided in NetApp Backup and Recovery when you activated the backup.

.Steps

. Follow the steps in the StorageGRID documentation to create the StorageGRID certificate.
+
https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-load-balancer-endpoints.html#attach-certificate[StorageGRID information on configuring certificates]
. Update StorageGRID with the certificate if you have not already done so.

. Log in to the Console agent as the root user. Run:
+
[source,shell]
----
sudo su
----

. Find the NetApp Backup and Recovery (Cloud Backup Service) Docker volume. Run:
+
[source,shell]
----
docker volume ls | grep cbs
----

+
Output example: 
+
----
local service-manager-2_cloudmanager_cbs_volume" 
----
+
NOTE: The volume name differs among Standard, Private, and Restricted deployment modes. This example uses Standard mode. Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].

. Find the mount point of the NetApp Backup and Recovery volume. Run:
+
[source,shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Output example: 
+
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data" 
----
+
NOTE: The mount point differs among Standard, Private, and Restricted deployment modes. This example shows a Standard cloud deployment. Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].

. Change to the mount point directory. Run:
+
[source,shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----

. If the StorageGRID certificate is signed by the root CA and an intermediate CA, append both `pem` files into one file named `sgws.crt` in the current location. Do not add the leaf certificate to this file.

=== Steps for the cloudmanager_cbs container

Enable StorageGRID server certificate verification in NetApp Backup and Recovery (Cloud Backup Service).

. Change to the Docker volume that you found in the earlier steps.
+
[source,shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data 
----

. Change to the config directory.
+
[source,shell]
----
cd cbs_config
----

. Create and save a configuration file as shown below with one of the following names, based on your deployment environment:
+
* `production-customer.json` for Standard mode and Restricted mode deployments
* `darksite-customer.json` for Private mode deployments
+
Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].
+
*Configuration file* 
+
[source,json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----

. Exit the container. Run: 
+
[source,shell]
----
exit
----

. Restart `cloudmanager_cbs`. Run:
+
[source,shell]
----
docker restart cloudmanager_cbs
---- 

=== Steps for the cloudmanager_cbs_catalog container

Next, enable StorageGRID server certificate verification for the Cataloging Service.

. Change to the Docker volume:
+
[source,shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data 
----

. Configure the catalog. Run: 
+
[source,shell]
----
cd cbs_catalog_config
----

. Create a configuration file as shown below with one of the following names, based on your deployment environment:
+
* `production-customer.json` for Standard mode and Restricted mode deployments
* `darksite-customer.json` for Private mode deployments
+
Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].
+
*Catalog configuration file* 
+
[source,json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  }
}
----

. Restart the catalog. Run:
+
[source,shell]
----
docker restart cloudmanager_cbs_catalog
----

=== Update the Console agent certificate with the StorageGRID certificate based on the agent operating system

==== Ubuntu
. Copy the SGWS certificate to `/usr/local/share/ca-certificates`. Here is an example:
+
[source,shell]
----
cp /config/sgws.crt /usr/local/share/ca-certificates/ 
----
+
where `sgws.crt` is the root CA certificate.

. Update the host certificates with the StorageGRID certificate. Run:
+
[source,shell]
----
sudo update-ca-certificates
----

==== Red Hat Enterprise Linux

. Copy the SGWS certificate to `/etc/pki/ca-trust/source/anchors/`.
+
[source,shell]
----
cp /config/sgws.crt /etc/pki/ca-trust/source/anchors/
----
+
where `sgws.crt` is the root CA certificate.

. Update the host certificates with the StorageGRID certificate.
+
[source,shell]
----
update-ca-trust extract
----

. Update the `ca-bundle.crt`
+
[source,shell]
----
cd /etc/pki/tls/certs/ 
openssl x509 -in ca-bundle.crt -text -noout
----

. To check whether the certificates are present, run the following command:
+
[source,shell]
----
openssl crl2pkcs7 -nocrl -certfile /etc/pki/tls/certs/ca-bundle.crt | openssl pkcs7 -print_certs | grep subject | head
----

== Create a CA certificate for ONTAP

If communication between the NetApp Backup and Recovery containers and ONTAP should validate the ONTAP certificate, complete the following steps.

NetApp Backup and Recovery uses the cluster management IP address to connect to ONTAP. Enter the cluster IP address in the Subject Alternative Name fields of the certificate. Specify this value when you generate the CSR in System Manager.

Use the System Manager documentation to create a new CA certificate for ONTAP. 

* https://docs.netapp.com/us-en/ontap/authentication/manage-certificates-sm-task.html[Manage certificates with System Manager]
* https://kb.netapp.com/on-prem/ontap/DM/System_Manager/SM-KBs/How_to_manage_ONTAP_SSL_certificates_via_System_Manager[How to manage ONTAP SSL certificates with System Manager]

.Steps

. Log in to the Console agent as root. Run:
+
[source,shell]
----
sudo su
----

. Find the NetApp Backup and Recovery Docker volume. Run:
+
[source,shell]
----
docker volume ls | grep cbs
----
+
Output example: 
+
----
local service-manager-2_cloudmanager_cbs_volume
----

+
NOTE: The volume name differs among Standard, Private, and Restricted deployment modes. This example shows a Standard cloud deployment. Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].

. Find the mount point for the volume. Run:
+
[source,shell]
----
docker volume inspect service-manager-2_cloudmanager_cbs_volume | grep Mountpoint
----
+
Output example: 
+
----
"Mountpoint": "/var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
----
+
NOTE: The mount point differs among Standard, Private, and Restricted deployment modes. This example shows a Standard cloud deployment. Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].

. Change to the mount point directory. Run:
+
[source,shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
---- 
+
. Complete one of the following steps:
* If the ONTAP certificate is signed by the root CA and an intermediate CA, then append the `pem` files of both into one file named `ontap.crt` in the current location.

* If the ONTAP certificate is signed by a single CA, then rename the `pem` file as `ontap.crt` and copy it in the current location. Do not add the leaf certificate to this file.

=== Steps for the cloudmanager_cbs container

Next, enable ONTAP server certificate verification in NetApp Backup and Recovery (Cloud Backup Service).
 
. Change to the Docker volume that you found in the earlier steps.
+
[source,shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data
---- 

. Change to the config directory. Run:
+
[source,shell]
----
cd cbs_config
----

. Create a configuration file as shown below with one of the following names, based on your deployment environment:
+
* `production-customer.json` for Standard mode and Restricted mode deployments
* `darksite-customer.json` for Private mode deployments
+
Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].
+
*Configuration file*
+
[source,json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----
+
. Exit the container. Run:
+
[source,shell]
----
exit
----

. Restart NetApp Backup and Recovery. Run:
+
[source,shell]
----
docker restart cloudmanager_cbs
----

=== Steps for the cloudmanager_cbs_catalog container

Enable ONTAP server certificate verification for the Cataloging Service.

. Change to the Docker volume. Run:
+
[source,shell]
----
cd /var/lib/docker/volumes/service-manager-2_cloudmanager_cbs_volume/_data 
----

. Run: 
+
[source,shell]
----
cd cbs_catalog_config
----

. Create a configuration file as shown below with one of the following names, based on your deployment environment:
+
* `production-customer.json` for Standard mode and Restricted mode deployments
* `darksite-customer.json` for Private mode deployments
+
Refer to https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html[NetApp Console deployment modes].
+
*Configuration file*
+
[source,json]
----
{
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----

. Restart NetApp Backup and Recovery. Run: 
+
[source,shell]
----
docker restart cloudmanager_cbs_catalog
----

== Create a certificate for both ONTAP and StorageGRID

If you need to enable the certificate for both ONTAP and StorageGRID, then the configuration file looks like this:

*Configuration file for both ONTAP and StorageGRID*
[source,json]
----
{
  "protocols": {
    "sgws": {
      "certificates": {
        "reject-unauthorized": true,
        "ca-bundle": "/config/sgws.crt"
      }
    }
  },
  "ontap": {
    "certificates": {
      "reject-unauthorized": true,
      "ca-bundle": "/config/ontap.crt"
    }
  }
}
----