---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, NetApp Backup and Recovery, protection, sql server, workloads, volumes, snapshots
summary: Learn what's new in NetApp Backup and Recovery.
---
= What's new in NetApp Backup and Recovery
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in NetApp Backup and Recovery.

== 09 February 2026

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2026-02-09.adoc[]

== 19 January 2026

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2026-01-19.adoc[]

== 08 December 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-12-08.adoc[]

== 06 October 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-10-06.adoc[]

== 25 August 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-08-25.adoc[]

== 12 August 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-08-11.adoc[]

== 28 July 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-07-28.adoc[]

== 14 July 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-06-07.adoc[]

== 09 June 2025 

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-06-09.adoc[]

== 13 May 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-05-12.adoc[]

== 16 April 2025

This NetApp Backup and Recovery release includes the following updates. 

include::_whatsnew/2025-04-16.adoc[]

== 17 March 2025 

This NetApp Backup and Recovery release includes the following updates. 

include::_whatsnew/2025-03-17.adoc[]

== 21 February 2025 

This NetApp Backup and Recovery release includes the following updates. 

include::_whatsnew/2025-02-18.adoc[]

== 13 February 2025

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2025-02-05.adoc[]    

== 22 November 2024

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2024-11-22.adoc[]

== 27 September 2024

This NetApp Backup and Recovery release includes the following updates.

include::_whatsnew/2024-09-27.adoc[]




