=== NetApp Backup and Recovery Preview Release   

This Preview release of NetApp Backup and Recovery provides an updated user interface that enables you to manage Microsoft SQL Server workloads using a 3-2-1 protection strategy, familiar in NetApp Backup and Recovery. With this new version, you can back up these workloads to primary storage, replicate them to secondary storage, and back them up to cloud object storage. 

NOTE: This documentation is provided as a technology preview.  With this preview offering, NetApp reserves the right to modify offering details, contents, and timeline before General Availability.  

This version of NetApp Backup and Recovery Preview 2025 includes the following updates.

* A redesigned user interface that provides a more intuitive experience for managing your backup and recovery tasks.
* The Preview version enables you to back up and restore Microsoft SQL Server databases. (Support for other workloads will be added in future releases.)
* This version integrates SnapCenter capabilities, enabling you to manage and protect your SnapCenter resources with a 3-2-1 data protection strategy from the NetApp Backup and Recovery user interface.
* This version enables you to import SnapCenter workloads into NetApp Backup and Recovery.  