=== BlueXP backup and recovery is now NetApp Backup and Recovery
 
BlueXP backup and recovery has been renamed to NetApp Backup and Recovery.
 
=== BlueXP is now NetApp Console
 
BlueXP has been renamed and redesigned to better reflect the role it has in managing your data infrastructure.
 
The NetApp Console (formerly BlueXP) provides centralized management of storage and data services across on-premises and cloud environments at enterprise grade—delivering real-time insights, faster workflows, and simplified administration. For details on what's changed, see the https://docs.netapp.com/us-en/bluexp-relnotes/index.html[NetApp Console release notes].

=== Oracle workload support as a Preview

This release of of NetApp Backup and Recovery introduces support for discovering and managing Oracle workloads:

* Discover Oracle databases
* Create protection policies for data only or data and log backups
* Protect databases with a 3-2-1 backup scheme
* Configure backup retention
* Mount and unmount ARCHIVELOG backups
* SAN Protocol support
* Standalone, ASM support
* Virtualized databases
* Search and restore database backups
* Oracle dashboard support
* Bulk protection of databases

For details about protecting Oracle workloads, refer to https://docs.netapp.com/us-en/bluexp-backup-recovery/br-use-oracle-protect-overview.html[Protect Oracle workloads overview].