=== Hyper-V workloads enhancements
In this release, Hyper-V workloads introduces the following enhancements:

* *Protect VMs on SAN storage*: You can now protect VMs on SAN object storage.
* *Restore to alternate location enhancements*: You can now restore to an alternate location from primary and secondary locations for VMs on SAN storage.
* *Restore files and folders to a guest VM*: You can now restore files and folders from a snapshot on primary storage to a guest Windows VM. This capability is supported only for CIFS VMs.

For details about protecting Hyper-V workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html[Protect Hyper-V workloads overview].

=== KVM workloads enhancements
In this release, KVM workloads introduces the following enhancement:

*Restore to alternate location*: You can now restore KVM VMs to an alternate destination (this feature is now generally available).

For details about protecting KVM workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-protect-overview.html[Protect KVM workloads overview].

=== Oracle Database workloads enhancements
In this release, Oracle Database workloads introduces the following enhancements:

* *Oracle AI Database 26ai support*: Backup and Recovery now supports Oracle AI Database 26ai.
* *Backup verification support*: You can now configure backup policies to automatically verify the integrity of your Oracle database backups.

For details about protecting Oracle Database workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html[Protect Oracle Database workloads overview].

=== VMware workloads enhancements
In this release, VMware workloads introduces the following enhancements:

* *Spanning datastore support for protection groups*: You can now choose the behavior of protection groups when protecting virtual machines whose virtual disks span multiple datastores.
* *Clone support*: You can now create clones of virtual machine snapshots from primary and secondary storage.

For details about protecting VMware workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html[Protect VMware workloads overview].