=== Oracle Database workloads enhancements
In this release, Oracle Database workloads introduces the following enhancements:

* *Clustered host support*: You can now discover and protect Oracle Real Application Clusters (RAC) databases that use Oracle Automatic Storage Management (ASM) and are deployed using VMDK on VMFS file systems.

For details about protecting Oracle Database workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html[Protect Oracle Database workloads overview].

=== VMware workloads enhancements

////
=== Kubernetes application protection enhancements
In this release, Kubernetes application protection introduces the following enhancements:

* *Kubernetes workloads are now Kubernetes applications*: Kubernetes workloads are now referred to as Kubernetes applications in the Backup and Recovery documentation. When you protect Kubernetes applications using Backup and Recovery, application data and metadata are protected.

For details about protecting Kubernetes applications, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html[Protect Kubernetes applications overview].
////
