=== General NetApp Backup and Recovery enhancement
In this release, KVM, Hyper-V, and VMware workloads introduce the following enhancement:

*Console Role-Based Access Control (RBAC) support*: The Hyper-V, KVM, and VMware workloads now support the NetApp Console framework for RBAC, enabling you to manage access to individual Hyper-V, KVM, or VMware hosts.

https://docs.netapp.com/us-en/data-services-backup-recovery/br-rbac-setup.html[Learn more about using RBAC in NetApp Backup and Recovery].

=== ONTAP Volumes workloads enhancement
In this release, ONTAP Volumes workloads introduces the following preview enhancement:

*Cloud Volumes ONTAP Azure Entra ID support*: You can now use Microsoft Entra ID authentication for Azure object storage bucket configurations if you don't want to use the storage account access key for Azure authentication. This option is supported for Cloud Volumes ONTAP in Azure systems running ONTAP 9.16.1 or later.

For details about protecting ONTAP Volumes workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html[Learn about ONTAP volume protection with NetApp Backup and Recovery]. 

=== VMware workloads enhancement
In this release, VMware workloads introduces the following enhancement:

*Google Cloud NetApp Volumes Flex Unified support*: NetApp Backup and Recovery for VMware workloads now supports the the Flex Unified service level for Google Cloud NetApp Volumes. Flex Unified is supported in ONTAP-mode only.

For details about protecting VMware workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html[Protect VMware workloads with NetApp Backup and Recovery].