=== General NetApp Backup and Recovery enhancements

* *Support for NetApp Console local deployment*: This release of NetApp Backup and Recovery supports NetApp Console local deployment in preview status.
* *90 days of job retention*: Backup and Recovery now retains job information in the Job Monitor for 90 days.

=== VMware workloads enhancements
In this release, VMware workloads introduces the following enhancements:

//* *Credential feature*: You can now use credentials. Feature not shipping August 10.
* *Restore to alternate location support for SAN VMs*: You can now restore SAN-based VM backups to an alternate location.
* *Multiple backup delete support*: You can now delete multiple backups at a time.

For details about protecting VMware workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html[Protect VMware workloads overview].

=== Kubernetes workloads enhancements
In this release, Kubernetes workloads introduces the following enhancements:

* *Preview support for air-gapped resources*: If running NetApp Backup and Recovery in NetApp Console local deployment, you can discover, protect, and restore air-gapped Kubernetes resources. This feature is in preview for this release.

For details about protecting Kubernetes workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html[Protect Kubernetes workloads overview].

=== ONTAP Volumes workloads enhancements
In this release, ONTAP Volumes workloads introduces the following enhancements:

* *Prioritize restore jobs over backups*: You can now prioritize restore jobs over backup jobs when you restore VMs or files.
* *Discover ONTAP systems and volumes without Backup and Recovery activation*: You can now discover systems and volumes without activating Backup and Recovery.

For details about protecting ONTAP Volumes workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html[Protect ONTAP Volumes workloads overview].