=== Hyper-V workloads enhancements
In this release, Hyper-V workloads introduces the following enhancements:

* *Hyper-V SAN object store backup and restore*: You can now protect Hyper-V VMs on SAN object storage.
* *Hyper-V SAN restore to alternate location enhancements*: You can now restore to an alternate location from primary, secondary, and object store locations for Hyper-V VMs on SAN storage.
* *Hyper-V file and folder restore for CIFS*: You can now restore files and folders from backups stored on CIFS shares.

For details about protecting Hyper-V workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html[Protect Hyper-V workloads overview].

=== KVM workloads enhancements
In this release, KVM workloads introduces the following enhancement:

* *Restore to alternate location*: You can now restore KVM VMs to an alternate destination (this feature is now generally available). For more information, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kvm-restore.html[Restore KVM virtual machines with NetApp Backup and Recovery].

=== Oracle Database workloads enhancements
In this release, Oracle Database workloads introduces the following enhancements:

* *Oracle AI Database 26ai support*: Backup and Recovery now supports Oracle AI Database 26ai.
* *Backup verification support*: You can now verify the integrity of your Oracle database backups.

For details about protecting Oracle Database workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html[Protect Oracle Database workloads overview].

=== VMware workloads enhancements
In this release, VMware workloads introduces the following enhancement:

*Protection groups can span datastores*: VMware workloads now supports creating protection groups that span more than one datastore.

For details about protecting VMware workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html[Protect VMware workloads overview].