=== Microsoft Hyper-V workloads supported in General Availability (GA)
Microsoft Hyper-V workload support is now generally available (GA) in NetApp Backup and Recovery.

=== VMware workloads supported in General Availability (GA)
VMware workload support is now generally available (GA) in NetApp Backup and Recovery.

=== Kubernetes workloads enhancements
This release of Kubernetes workloads introduces the following enhanced capabilities:

* *CR workflow support*: You can now perform common protection tasks using CRs as well as the Backup and Recovery web UI.
* *Cluster migration*: You can now add existing Kubernetes clusters protected with Trident Protect to Backup and Recovery.
* *Alerting framework support*: You can now receive email and UI alerts for certain Kubernetes workload events.
* *Restore tab integration*: You can now access the Kubernetes workload restore actions from the Restore menu.
* *Support for the 3-2-1 fanout backup architecture*: You can now use a 3-2-1 fanout architecture in your protection policy when protecting Kubernetes workloads.

For details about protecting Kubernetes workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html[Protect Kubernetes workloads overview].

=== Oracle Database workloads enhancements
This release of Oracle Database workloads introduces the following enhanced capabilities:

* *Non-root user support*: Non-root users can now perform backup, restore, and clone operations, improving security and compliance.
* *Clone support*: Clone capabilities are now supported across primary and secondary NAS, SAN, and ASM environments using ASM library v2, enabling coordinated protection workflows.
* *Clone split support*: You can now split writable snapshots (clones) from their parent volumes, freeing up storage and enabling independent operations.
* *Backup and restore for object store*: Native backup and restore capabilities are now supported for object-based S3-compatible storage targets.
* *Clone Lifecycle Management (CLM)*: Clone refresh operations are supported on primary storage.
* *Clone to alternate host*: You can now clone databases to a different host (for testing or analytics) from both primary and secondary storage.
* *ONTAP consistency group support*: ONTAP consistency groups are now supported, ensuring application-consistent snapshots across multiple volumes.
* Backup and Recovery now supports the following protection policy architectures for Oracle Database workloads:
** 3-2-1 fanout
** Disk to disk
** Disk to object storage
** Cascading
** Local snapshot

For details about protecting Oracle Database workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html[Protect Oracle Database workloads overview].