=== Kubernetes workloads enhancements
In this release, Kubernetes workloads introduces the following enhancements:

* *Trident Protect 26.08*: This release includes Trident Protect 26.08.
* *Backup retries*: You can now enable backup retries and configure the number of retry attempts and intervals between retries as advanced settings in Kubernetes protection policies.
* *Partial backup success*: You can now configure advanced settings in Kubernetes protection policies to continue backing up when individual resources fail, allowing backup jobs to complete as partially successful. This enables you to restore backed-up resources even if some resources fail during the backup operation.
* *Crash-consistent and VM-consistent backups*: Backup and Recovery for NetApp Console service now supports configuring protection policies that create crash-consistent or VM-consistent backups or snapshots. You can also customize how VM freezes are performed during the protection operation.
* *Reconnect Kubernetes cluster upon Console agent IP change*: Backup and Recovery for NetApp Console service now enables you to reconnect a cluster to its Console agent if the IP address of the agent changes.
* *Migrate cluster to new Console agent*: Backup and Recovery for NetApp Console service now enables you to migrate a cluster to a new Console agent if the original agent fails or is deleted, ensuring uninterrupted app protection.

For details about protecting Kubernetes workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html[Protect Kubernetes workloads overview].

=== Oracle Database workloads enhancements
In this release, Oracle Database workloads introduces the following enhancements:

* *Pluggable Database (PDB) restore and clone*: Backup and Recovery for NetApp Console service now supports restoring and cloning pluggable databases.

For details about protecting Oracle Database workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html[Protect Oracle Database workloads overview].