=== General NetApp Backup and Recovery enhancements
In this release, KVM, Hyper-V, and VMware workloads introduce the following enhancement:

*Credential selection during VM host discovery*: When you register a KVM, Hyper-V, or VMware host, you can now select credentials that you have already added to Backup and Recovery.

=== VMware workloads enhancements
In this release, VMware workloads introduces the following enhancement:



For details about protecting VMware workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html[Protect VMware workloads with NetApp Backup and Recovery].

=== Hyper-V workloads enhancements
In this release, Hyper-V workloads introduces the following enhancement:

*Spanning support*: NetApp Backup and Recovery now supports protecting VMs that have been spanned across disks.

For details about protecting Hyper-V workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html[Learn about protecting Hyper-V workloads with NetApp Backup and Recovery].

=== ONTAP Volumes workloads enhancements
In this release, ONTAP Volumes workloads introduces the following enhancements:

* *Azure EntraID support for Cloud Volumes ONTAP*: NetApp Backup and Recovery now supports Entra ID authentication for Cloud Volumes ONTAP.
* *Customized job reporting*: You can now customize job reports.
* *Ability to cancel restore job*: You can now cancel ongoing volume restore operations from the Job Monitor.
* *China region support for Microsoft Azure volumes*: NetApp Backup and Recovery now supports protecting volumes on Azure systems deployed in China.
* *Catalog indexing status improvements*: Catalog indexing status indications have been improved.
* *Support for NetApp AFX storage*: You can now protect volumes on 2- or 4-node NetApp AFX storage systems with NetApp Backup and Recovery.

For details about protecting ONTAP Volumes workloads, refer to https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html[Learn about ONTAP volume protection with NetApp Backup and Recovery].