
//== Prepare your ONTAP clusters
You'll need to prepare your source on-premises ONTAP system and any secondary on-premises ONTAP or Cloud Volumes ONTAP systems.

Preparing your ONTAP clusters involves the following steps: 

* Discover your ONTAP systems in NetApp Console
* Verify ONTAP system requirements
* Verify ONTAP networking requirements for backing up data to object storage
* Verify ONTAP networking requirements for replicating volumes

// This is an include along with the 2 subsections of "Discover your ONTAP cluster in BlueXP" and "Verify ONTAP requirements"


=== Discover your ONTAP systems in NetApp Console
Both your source on-premises ONTAP system and any secondary on-premises ONTAP or Cloud Volumes ONTAP systems must be available on the NetApp Console *Systems* page.

You'll need to know the cluster management IP address and the password for the admin user account to add the cluster.
https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html[Learn how to discover a cluster^].



=== Verify ONTAP system requirements
Ensure that the following ONTAP requirements are met: 

* Minimum of ONTAP 9.8; ONTAP 9.8P13 and later is recommended.
* A SnapMirror license (included as part of the Premium Bundle or Data Protection Bundle).
+
*Note:* The "Hybrid Cloud Bundle" is not required when using NetApp Backup and Recovery.
+
Learn how to https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html[manage your cluster licenses^].

* Time and time zone are set correctly. Learn how to https://docs.netapp.com/us-en/ontap/system-admin/manage-cluster-time-concept.html[configure your cluster time^].
* If you are going to replicate data, you should verify that the source and destination systems are running compatible ONTAP versions before replicating data.
+
https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html[View compatible ONTAP versions for SnapMirror relationships^].